// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: carvel.dev/kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	v1alpha1 "carvel.dev/kapp-controller/pkg/apis/kappctrl/v1alpha1"
	proto "github.com/gogo/protobuf/proto"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *AppTemplateSpec) Reset()      { *m = AppTemplateSpec{} }
func (*AppTemplateSpec) ProtoMessage() {}
func (*AppTemplateSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{0}
}
func (m *AppTemplateSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppTemplateSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *AppTemplateSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppTemplateSpec.Merge(m, src)
}
func (m *AppTemplateSpec) XXX_Size() int {
	return m.Size()
}
func (m *AppTemplateSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_AppTemplateSpec.DiscardUnknown(m)
}

var xxx_messageInfo_AppTemplateSpec proto.InternalMessageInfo

func (m *IncludedSoftware) Reset()      { *m = IncludedSoftware{} }
func (*IncludedSoftware) ProtoMessage() {}
func (*IncludedSoftware) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{1}
}
func (m *IncludedSoftware) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IncludedSoftware) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *IncludedSoftware) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncludedSoftware.Merge(m, src)
}
func (m *IncludedSoftware) XXX_Size() int {
	return m.Size()
}
func (m *IncludedSoftware) XXX_DiscardUnknown() {
	xxx_messageInfo_IncludedSoftware.DiscardUnknown(m)
}

var xxx_messageInfo_IncludedSoftware proto.InternalMessageInfo

func (m *Maintainer) Reset()      { *m = Maintainer{} }
func (*Maintainer) ProtoMessage() {}
func (*Maintainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{2}
}
func (m *Maintainer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Maintainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Maintainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Maintainer.Merge(m, src)
}
func (m *Maintainer) XXX_Size() int {
	return m.Size()
}
func (m *Maintainer) XXX_DiscardUnknown() {
	xxx_messageInfo_Maintainer.DiscardUnknown(m)
}

var xxx_messageInfo_Maintainer proto.InternalMessageInfo

func (m *Package) Reset()      { *m = Package{} }
func (*Package) ProtoMessage() {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{3}
}
func (m *Package) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return m.Size()
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *PackageList) Reset()      { *m = PackageList{} }
func (*PackageList) ProtoMessage() {}
func (*PackageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{4}
}
func (m *PackageList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageList.Merge(m, src)
}
func (m *PackageList) XXX_Size() int {
	return m.Size()
}
func (m *PackageList) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageList.DiscardUnknown(m)
}

var xxx_messageInfo_PackageList proto.InternalMessageInfo

func (m *PackageMetadata) Reset()      { *m = PackageMetadata{} }
func (*PackageMetadata) ProtoMessage() {}
func (*PackageMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{5}
}
func (m *PackageMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageMetadata.Merge(m, src)
}
func (m *PackageMetadata) XXX_Size() int {
	return m.Size()
}
func (m *PackageMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PackageMetadata proto.InternalMessageInfo

func (m *PackageMetadataList) Reset()      { *m = PackageMetadataList{} }
func (*PackageMetadataList) ProtoMessage() {}
func (*PackageMetadataList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{6}
}
func (m *PackageMetadataList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageMetadataList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageMetadataList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageMetadataList.Merge(m, src)
}
func (m *PackageMetadataList) XXX_Size() int {
	return m.Size()
}
func (m *PackageMetadataList) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageMetadataList.DiscardUnknown(m)
}

var xxx_messageInfo_PackageMetadataList proto.InternalMessageInfo

func (m *PackageMetadataSpec) Reset()      { *m = PackageMetadataSpec{} }
func (*PackageMetadataSpec) ProtoMessage() {}
func (*PackageMetadataSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{7}
}
func (m *PackageMetadataSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageMetadataSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageMetadataSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageMetadataSpec.Merge(m, src)
}
func (m *PackageMetadataSpec) XXX_Size() int {
	return m.Size()
}
func (m *PackageMetadataSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageMetadataSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PackageMetadataSpec proto.InternalMessageInfo

func (m *PackageSpec) Reset()      { *m = PackageSpec{} }
func (*PackageSpec) ProtoMessage() {}
func (*PackageSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{8}
}
func (m *PackageSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageSpec.Merge(m, src)
}
func (m *PackageSpec) XXX_Size() int {
	return m.Size()
}
func (m *PackageSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PackageSpec proto.InternalMessageInfo

func (m *ValuesSchema) Reset()      { *m = ValuesSchema{} }
func (*ValuesSchema) ProtoMessage() {}
func (*ValuesSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{9}
}
func (m *ValuesSchema) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValuesSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ValuesSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuesSchema.Merge(m, src)
}
func (m *ValuesSchema) XXX_Size() int {
	return m.Size()
}
func (m *ValuesSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuesSchema.DiscardUnknown(m)
}

var xxx_messageInfo_ValuesSchema proto.InternalMessageInfo

func (m *VersionSelection) Reset()      { *m = VersionSelection{} }
func (*VersionSelection) ProtoMessage() {}
func (*VersionSelection) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0bf4d4d6edd19a, []int{10}
}
func (m *VersionSelection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionSelection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VersionSelection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionSelection.Merge(m, src)
}
func (m *VersionSelection) XXX_Size() int {
	return m.Size()
}
func (m *VersionSelection) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionSelection.DiscardUnknown(m)
}

var xxx_messageInfo_VersionSelection proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AppTemplateSpec)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.AppTemplateSpec")
	proto.RegisterType((*IncludedSoftware)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.IncludedSoftware")
	proto.RegisterType((*Maintainer)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.Maintainer")
	proto.RegisterType((*Package)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.Package")
	proto.RegisterType((*PackageList)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageList")
	proto.RegisterType((*PackageMetadata)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageMetadata")
	proto.RegisterType((*PackageMetadataList)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageMetadataList")
	proto.RegisterType((*PackageMetadataSpec)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageMetadataSpec")
	proto.RegisterType((*PackageSpec)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageSpec")
	proto.RegisterType((*ValuesSchema)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.ValuesSchema")
	proto.RegisterType((*VersionSelection)(nil), "carvel.dev.kapp_controller.pkg.apiserver.apis.datapackaging.v1alpha1.VersionSelection")
}

func init() {
	proto.RegisterFile("carvel.dev/kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1/generated.proto", fileDescriptor_ff0bf4d4d6edd19a)
}

var fileDescriptor_ff0bf4d4d6edd19a = []byte{
	// 1156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0x26, 0x2e, 0x76, 0xc6, 0x29, 0x31, 0x53, 0x10, 0x96, 0x0f, 0xeb, 0xc8, 0x17, 0x52,
	0xa4, 0xac, 0x69, 0x68, 0xab, 0x4a, 0x9c, 0xe2, 0x04, 0xa1, 0xd0, 0xa6, 0x8d, 0xc6, 0x55, 0x54,
	0x10, 0x6a, 0x98, 0xac, 0x5f, 0xec, 0xa9, 0xf7, 0x63, 0x3a, 0x33, 0x76, 0x09, 0x07, 0x84, 0xc4,
	0xd7, 0x0d, 0xb8, 0x71, 0xe0, 0xc2, 0x9d, 0x4b, 0xff, 0x8c, 0x88, 0x53, 0x4f, 0xa8, 0xa7, 0x88,
	0x18, 0x89, 0xbf, 0x00, 0xee, 0x68, 0xc7, 0xe3, 0xdd, 0xf5, 0x1a, 0x37, 0x25, 0x92, 0x73, 0x1b,
	0xbf, 0xaf, 0xdf, 0xfb, 0xbd, 0xf7, 0xe6, 0xed, 0x18, 0x75, 0xda, 0x4c, 0x75, 0x7a, 0x07, 0x8e,
	0x1b, 0xfa, 0xf5, 0xbe, 0xff, 0x84, 0x0a, 0x58, 0x53, 0x34, 0xf8, 0xbc, 0x57, 0x77, 0xa9, 0xe8,
	0x83, 0xb7, 0xd6, 0xa5, 0x9c, 0xaf, 0xb9, 0x61, 0xa0, 0x44, 0xe8, 0x79, 0x20, 0xea, 0xbc, 0xdb,
	0xae, 0x53, 0xce, 0x24, 0x88, 0x3e, 0x08, 0x7d, 0xaa, 0xb7, 0xa8, 0xa2, 0x9c, 0xba, 0x5d, 0xda,
	0x66, 0x41, 0xbb, 0xde, 0xbf, 0x46, 0x3d, 0xde, 0xa1, 0xd7, 0xea, 0x6d, 0x08, 0x40, 0x50, 0x05,
	0x2d, 0x87, 0x8b, 0x50, 0x85, 0xf8, 0x41, 0x82, 0xe4, 0x0c, 0x91, 0xf6, 0x35, 0x92, 0x33, 0x44,
	0xda, 0x8f, 0x90, 0xf6, 0x13, 0x24, 0x87, 0x77, 0xdb, 0x4e, 0x8c, 0xa4, 0x4f, 0xce, 0x18, 0x92,
	0x33, 0x42, 0xaa, 0xac, 0xa5, 0x38, 0xb4, 0xc3, 0x76, 0x58, 0xd7, 0x80, 0x07, 0xbd, 0x43, 0xfd,
	0x4b, 0xff, 0xd0, 0xa7, 0x61, 0x22, 0x95, 0x8f, 0xce, 0x49, 0xb9, 0x1e, 0x29, 0x5c, 0x25, 0xbc,
	0xa9, 0x1c, 0x2b, 0xd7, 0xbb, 0xb7, 0xa4, 0xc3, 0xc2, 0xc8, 0xdc, 0xa7, 0x6e, 0x87, 0x05, 0x20,
	0x8e, 0x12, 0x7f, 0x1f, 0x14, 0xad, 0xf7, 0x27, 0xbd, 0xea, 0xd3, 0xbc, 0x44, 0x2f, 0x50, 0xcc,
	0x87, 0x09, 0x87, 0x9b, 0x67, 0x39, 0x48, 0xb7, 0x03, 0x3e, 0xcd, 0xfa, 0xd5, 0xbe, 0xb2, 0xd0,
	0xf2, 0x06, 0xe7, 0xf7, 0xc1, 0xe7, 0x1e, 0x55, 0xd0, 0xe4, 0xe0, 0x62, 0x8e, 0x72, 0x92, 0x83,
	0x5b, 0xb6, 0x56, 0xac, 0xd5, 0xe2, 0x3a, 0x71, 0xce, 0xd9, 0x25, 0x67, 0x54, 0x9c, 0xb8, 0x2d,
	0xce, 0x06, 0xe7, 0x11, 0x42, 0xa3, 0x30, 0x38, 0xa9, 0xe6, 0xa2, 0x13, 0xd1, 0x48, 0xb5, 0x5f,
	0x2d, 0x54, 0xda, 0x0e, 0x5c, 0xaf, 0xd7, 0x82, 0x56, 0x33, 0x3c, 0x54, 0x11, 0x08, 0xbe, 0x81,
	0x8a, 0x2d, 0x26, 0xb9, 0x47, 0x8f, 0xee, 0x52, 0x1f, 0x74, 0x36, 0x8b, 0x8d, 0x2b, 0xc7, 0x27,
	0xd5, 0xb9, 0xc1, 0x49, 0xb5, 0xb8, 0x95, 0xa8, 0x48, 0xda, 0x0e, 0x5f, 0x45, 0xf9, 0x3e, 0x08,
	0xc9, 0xc2, 0xa0, 0x3c, 0xaf, 0x5d, 0x96, 0x8d, 0x4b, 0x7e, 0x6f, 0x28, 0x26, 0x23, 0xbd, 0x46,
	0x00, 0xe9, 0x0a, 0xc6, 0x55, 0x64, 0xbe, 0x90, 0x41, 0x48, 0x54, 0x24, 0x6d, 0x57, 0x73, 0x10,
	0xda, 0xa1, 0x2c, 0x50, 0x34, 0xaa, 0x32, 0x5e, 0x41, 0xb9, 0x20, 0xc9, 0x6f, 0xc9, 0x78, 0xe7,
	0x74, 0x62, 0x5a, 0x53, 0xfb, 0xc7, 0x42, 0xf9, 0x5d, 0x3d, 0xa3, 0x80, 0x3f, 0x45, 0x85, 0xa8,
	0xe7, 0xd1, 0xd8, 0x9a, 0xfa, 0xbe, 0xe3, 0x0c, 0x5b, 0xe7, 0xa4, 0x5b, 0x97, 0x14, 0x31, 0xb2,
	0x76, 0xfa, 0xd7, 0x9c, 0x7b, 0x07, 0x8f, 0xc0, 0x55, 0x3b, 0xa0, 0x68, 0x03, 0x1b, 0x0c, 0x94,
	0xc8, 0x48, 0x1c, 0x15, 0x7f, 0x67, 0x99, 0xf6, 0xcd, 0xeb, 0xf0, 0xe0, 0xcc, 0xea, 0x92, 0x39,
	0x86, 0x93, 0xee, 0x68, 0xcc, 0x3b, 0xd5, 0xd5, 0xbf, 0x2d, 0x54, 0x34, 0x36, 0x77, 0x98, 0x54,
	0xf8, 0x93, 0x09, 0xee, 0xce, 0xcb, 0x71, 0x8f, 0xbc, 0x35, 0xf3, 0x92, 0x41, 0x29, 0x8c, 0x24,
	0x29, 0xde, 0xdf, 0x5a, 0xe8, 0x12, 0x53, 0xe0, 0xcb, 0xf2, 0xfc, 0xca, 0xc2, 0x6a, 0x71, 0x9d,
	0xce, 0x9c, 0x78, 0xe3, 0xb2, 0x49, 0xe7, 0xd2, 0x76, 0x84, 0x4b, 0x86, 0xf0, 0xb5, 0x6f, 0xe6,
	0xd1, 0xb2, 0xb1, 0xd8, 0x19, 0x25, 0x37, 0xfb, 0xb6, 0xff, 0x30, 0xde, 0x76, 0x7f, 0xe6, 0xec,
	0x47, 0xdc, 0xa6, 0xb6, 0xff, 0xeb, 0x79, 0x74, 0x25, 0x63, 0x7b, 0x01, 0x63, 0xf0, 0x7d, 0x66,
	0x0c, 0xd8, 0x85, 0x15, 0x62, 0xca, 0x38, 0xfc, 0x95, 0x9b, 0x28, 0x83, 0xde, 0xb2, 0xe7, 0x5c,
	0x6f, 0x1b, 0x68, 0xd9, 0x0b, 0x83, 0x76, 0x6a, 0x39, 0x99, 0x35, 0xf7, 0xa6, 0x71, 0x5d, 0xbe,
	0x33, 0xae, 0x26, 0x59, 0x7b, 0xbc, 0x85, 0x4a, 0xb2, 0x13, 0x0a, 0xb5, 0x35, 0xb1, 0xfb, 0xca,
	0x26, 0x46, 0xa9, 0x99, 0xd1, 0x93, 0x09, 0x0f, 0xfc, 0x1e, 0xba, 0xcc, 0xdc, 0x30, 0x68, 0xee,
	0x7d, 0xd0, 0xa0, 0x12, 0x6e, 0x5e, 0x2f, 0xe7, 0x74, 0x88, 0x37, 0x4c, 0x88, 0xcb, 0xdb, 0x69,
	0x25, 0x19, 0xb7, 0xc5, 0xb7, 0xd0, 0x12, 0x17, 0x61, 0x9f, 0xb5, 0x40, 0x68, 0xf6, 0x97, 0xb4,
	0xef, 0xeb, 0xc6, 0x77, 0x69, 0x37, 0xa5, 0x23, 0x63, 0x96, 0xf8, 0x67, 0x0b, 0x15, 0xfd, 0x78,
	0xfb, 0xca, 0xf2, 0x2b, 0xba, 0xcb, 0xad, 0xd9, 0x75, 0x39, 0x59, 0xf5, 0x49, 0x77, 0x12, 0x99,
	0x24, 0xe9, 0x6c, 0xb0, 0x83, 0x90, 0x4b, 0x15, 0xb4, 0x43, 0xc1, 0x40, 0x96, 0xf3, 0x2b, 0x0b,
	0xab, 0x8b, 0x8d, 0x57, 0xa3, 0x3b, 0xbb, 0x19, 0x4b, 0x49, 0xca, 0x02, 0x7f, 0x88, 0xb0, 0xec,
	0x71, 0x9e, 0x69, 0x46, 0x41, 0x57, 0xa3, 0x62, 0xd0, 0x70, 0x73, 0xc2, 0x82, 0xfc, 0x87, 0x57,
	0xed, 0x29, 0x8a, 0xd7, 0xad, 0x1e, 0xb0, 0xab, 0x28, 0x2f, 0xe0, 0x30, 0x35, 0x5c, 0xf1, 0x87,
	0x90, 0x0c, 0xc5, 0x64, 0xa4, 0xff, 0x3f, 0xdf, 0xcc, 0x55, 0x54, 0xf0, 0x98, 0x0b, 0x81, 0x04,
	0x59, 0x5e, 0xd0, 0xfc, 0x96, 0x86, 0x37, 0x71, 0x28, 0x23, 0xb1, 0x16, 0x3f, 0x44, 0x48, 0x80,
	0x07, 0x54, 0x42, 0x6b, 0x43, 0xe9, 0xe9, 0x28, 0xae, 0xbf, 0xfd, 0x72, 0x37, 0xfd, 0x3e, 0xf3,
	0x21, 0xd9, 0x77, 0x24, 0x8e, 0x42, 0x52, 0x11, 0xf1, 0x63, 0x54, 0x75, 0xa3, 0x86, 0x31, 0x75,
	0x44, 0xe0, 0x71, 0x8f, 0x09, 0xf0, 0x21, 0x50, 0x32, 0x5d, 0xc8, 0xe1, 0x58, 0xbd, 0x65, 0x02,
	0x55, 0x37, 0x23, 0x73, 0xc5, 0xa6, 0x99, 0x93, 0xb3, 0xe2, 0x45, 0x63, 0x6b, 0x12, 0xb8, 0x1b,
	0x2a, 0x88, 0x86, 0x6f, 0x6c, 0x6c, 0x49, 0x4a, 0x47, 0xc6, 0x2c, 0xf1, 0x4f, 0x16, 0x2a, 0x28,
	0xf3, 0xc8, 0x2a, 0xe7, 0x75, 0x2d, 0x66, 0xb8, 0x99, 0x32, 0x2f, 0xba, 0x64, 0x61, 0x8e, 0xa4,
	0x24, 0x4e, 0x06, 0xff, 0x62, 0xa1, 0xa5, 0x3e, 0xf5, 0x7a, 0x20, 0x9b, 0xfa, 0x89, 0xa8, 0xa7,
	0xaf, 0xb8, 0x7e, 0x38, 0xbb, 0xec, 0xf6, 0x52, 0x68, 0x49, 0xf1, 0xd2, 0x52, 0x32, 0x96, 0x11,
	0x7e, 0x6a, 0xa1, 0x12, 0xcb, 0x3c, 0x0f, 0xcb, 0x8b, 0xfa, 0xe2, 0x3f, 0x9a, 0x5d, 0x9a, 0xd9,
	0x07, 0x69, 0xb2, 0x1d, 0xb3, 0x1a, 0x32, 0x91, 0x1d, 0xfe, 0xdd, 0x42, 0x76, 0x04, 0xbd, 0x19,
	0x23, 0x9b, 0x9b, 0xd4, 0x04, 0x0f, 0x5c, 0x3d, 0x9c, 0x48, 0xd7, 0x79, 0x86, 0x04, 0xb2, 0x88,
	0x8d, 0xda, 0xe0, 0xa4, 0x6a, 0xdf, 0x7e, 0x61, 0x56, 0xe4, 0x8c, 0xac, 0xf1, 0x6f, 0x16, 0xaa,
	0x74, 0x7b, 0x07, 0x20, 0x02, 0x50, 0x20, 0x27, 0x48, 0x15, 0x2f, 0x9c, 0x94, 0x3d, 0x38, 0xa9,
	0x56, 0x6e, 0x4f, 0xcd, 0x88, 0xbc, 0x20, 0xdb, 0x5a, 0x80, 0xc6, 0xc6, 0x0e, 0x3f, 0x44, 0x8b,
	0x21, 0x87, 0x60, 0x63, 0x77, 0xbb, 0xff, 0xae, 0x79, 0x9b, 0xac, 0x4d, 0xdd, 0x58, 0xe6, 0x9f,
	0x95, 0x43, 0xe8, 0x93, 0xf7, 0x3f, 0x53, 0x10, 0x44, 0xa1, 0x1b, 0xaf, 0x99, 0x19, 0x59, 0xbc,
	0x37, 0x8a, 0x43, 0x92, 0x90, 0xb5, 0x6d, 0x54, 0x9a, 0x28, 0xe8, 0x0d, 0x54, 0x74, 0xc3, 0x40,
	0x2a, 0x11, 0x7d, 0x46, 0x64, 0xf6, 0x1d, 0xb0, 0x99, 0xa8, 0x48, 0xda, 0xae, 0xf1, 0xc5, 0xf1,
	0xa9, 0x3d, 0xf7, 0xec, 0xd4, 0x9e, 0x7b, 0x7e, 0x6a, 0xcf, 0x7d, 0x39, 0xb0, 0xad, 0xe3, 0x81,
	0x6d, 0x3d, 0x1b, 0xd8, 0xd6, 0xf3, 0x81, 0x6d, 0xfd, 0x31, 0xb0, 0xad, 0x1f, 0xff, 0xb4, 0xe7,
	0x3e, 0x7e, 0x30, 0xab, 0xff, 0xf2, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xaf, 0x1f, 0xcd,
	0x26, 0x10, 0x00, 0x00,
}

func (m *AppTemplateSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppTemplateSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppTemplateSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Spec != nil {
		{
			size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IncludedSoftware) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IncludedSoftware) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IncludedSoftware) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Description)
	copy(dAtA[i:], m.Description)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Description)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Version)
	copy(dAtA[i:], m.Version)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Version)))
	i--
	dAtA[i] = 0x12
	i -= len(m.DisplayName)
	copy(dAtA[i:], m.DisplayName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DisplayName)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Maintainer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Maintainer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Maintainer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Name)
	copy(dAtA[i:], m.Name)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Name)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Package) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Package) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Package) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageMetadataList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageMetadataList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageMetadataList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageMetadataSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageMetadataSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageMetadataSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.SupportDescription)
	copy(dAtA[i:], m.SupportDescription)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.SupportDescription)))
	i--
	dAtA[i] = 0x42
	if len(m.Categories) > 0 {
		for iNdEx := len(m.Categories) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Categories[iNdEx])
			copy(dAtA[i:], m.Categories[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.Categories[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Maintainers) > 0 {
		for iNdEx := len(m.Maintainers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Maintainers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	i -= len(m.ProviderName)
	copy(dAtA[i:], m.ProviderName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ProviderName)))
	i--
	dAtA[i] = 0x2a
	i -= len(m.IconSVGBase64)
	copy(dAtA[i:], m.IconSVGBase64)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.IconSVGBase64)))
	i--
	dAtA[i] = 0x22
	i -= len(m.ShortDescription)
	copy(dAtA[i:], m.ShortDescription)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ShortDescription)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.LongDescription)
	copy(dAtA[i:], m.LongDescription)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.LongDescription)))
	i--
	dAtA[i] = 0x12
	i -= len(m.DisplayName)
	copy(dAtA[i:], m.DisplayName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DisplayName)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KubernetesVersionSelection != nil {
		{
			size, err := m.KubernetesVersionSelection.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.KappControllerVersionSelection != nil {
		{
			size, err := m.KappControllerVersionSelection.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if len(m.IncludedSoftware) > 0 {
		for iNdEx := len(m.IncludedSoftware) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.IncludedSoftware[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	{
		size, err := m.ValuesSchema.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.Template.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	i -= len(m.ReleaseNotes)
	copy(dAtA[i:], m.ReleaseNotes)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ReleaseNotes)))
	i--
	dAtA[i] = 0x32
	i -= len(m.CapactiyRequirementsDescription)
	copy(dAtA[i:], m.CapactiyRequirementsDescription)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.CapactiyRequirementsDescription)))
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.ReleasedAt.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Licenses) > 0 {
		for iNdEx := len(m.Licenses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Licenses[iNdEx])
			copy(dAtA[i:], m.Licenses[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.Licenses[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	i -= len(m.Version)
	copy(dAtA[i:], m.Version)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Version)))
	i--
	dAtA[i] = 0x12
	i -= len(m.RefName)
	copy(dAtA[i:], m.RefName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.RefName)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ValuesSchema) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValuesSchema) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValuesSchema) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.OpenAPIv3.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VersionSelection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionSelection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VersionSelection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Constraints)
	copy(dAtA[i:], m.Constraints)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Constraints)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AppTemplateSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Spec != nil {
		l = m.Spec.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *IncludedSoftware) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DisplayName)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Version)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Description)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *Maintainer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *Package) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PackageMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageMetadataList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PackageMetadataSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DisplayName)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.LongDescription)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.ShortDescription)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.IconSVGBase64)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.ProviderName)
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Maintainers) > 0 {
		for _, e := range m.Maintainers {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.Categories) > 0 {
		for _, s := range m.Categories {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	l = len(m.SupportDescription)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RefName)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Version)
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Licenses) > 0 {
		for _, s := range m.Licenses {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	l = m.ReleasedAt.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.CapactiyRequirementsDescription)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.ReleaseNotes)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Template.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.ValuesSchema.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.IncludedSoftware) > 0 {
		for _, e := range m.IncludedSoftware {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if m.KappControllerVersionSelection != nil {
		l = m.KappControllerVersionSelection.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.KubernetesVersionSelection != nil {
		l = m.KubernetesVersionSelection.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *ValuesSchema) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.OpenAPIv3.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VersionSelection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Constraints)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AppTemplateSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AppTemplateSpec{`,
		`Spec:` + strings.Replace(fmt.Sprintf("%v", this.Spec), "AppSpec", "v1alpha1.AppSpec", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *IncludedSoftware) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&IncludedSoftware{`,
		`DisplayName:` + fmt.Sprintf("%v", this.DisplayName) + `,`,
		`Version:` + fmt.Sprintf("%v", this.Version) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Maintainer) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Maintainer{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Package) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Package{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "PackageSpec", "PackageSpec", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]Package{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "Package", "Package", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&PackageList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageMetadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PackageMetadata{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "PackageMetadataSpec", "PackageMetadataSpec", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageMetadataList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]PackageMetadata{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "PackageMetadata", "PackageMetadata", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&PackageMetadataList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageMetadataSpec) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForMaintainers := "[]Maintainer{"
	for _, f := range this.Maintainers {
		repeatedStringForMaintainers += strings.Replace(strings.Replace(f.String(), "Maintainer", "Maintainer", 1), `&`, ``, 1) + ","
	}
	repeatedStringForMaintainers += "}"
	s := strings.Join([]string{`&PackageMetadataSpec{`,
		`DisplayName:` + fmt.Sprintf("%v", this.DisplayName) + `,`,
		`LongDescription:` + fmt.Sprintf("%v", this.LongDescription) + `,`,
		`ShortDescription:` + fmt.Sprintf("%v", this.ShortDescription) + `,`,
		`IconSVGBase64:` + fmt.Sprintf("%v", this.IconSVGBase64) + `,`,
		`ProviderName:` + fmt.Sprintf("%v", this.ProviderName) + `,`,
		`Maintainers:` + repeatedStringForMaintainers + `,`,
		`Categories:` + fmt.Sprintf("%v", this.Categories) + `,`,
		`SupportDescription:` + fmt.Sprintf("%v", this.SupportDescription) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageSpec) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForIncludedSoftware := "[]IncludedSoftware{"
	for _, f := range this.IncludedSoftware {
		repeatedStringForIncludedSoftware += strings.Replace(strings.Replace(f.String(), "IncludedSoftware", "IncludedSoftware", 1), `&`, ``, 1) + ","
	}
	repeatedStringForIncludedSoftware += "}"
	s := strings.Join([]string{`&PackageSpec{`,
		`RefName:` + fmt.Sprintf("%v", this.RefName) + `,`,
		`Version:` + fmt.Sprintf("%v", this.Version) + `,`,
		`Licenses:` + fmt.Sprintf("%v", this.Licenses) + `,`,
		`ReleasedAt:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ReleasedAt), "Time", "v1.Time", 1), `&`, ``, 1) + `,`,
		`CapactiyRequirementsDescription:` + fmt.Sprintf("%v", this.CapactiyRequirementsDescription) + `,`,
		`ReleaseNotes:` + fmt.Sprintf("%v", this.ReleaseNotes) + `,`,
		`Template:` + strings.Replace(strings.Replace(this.Template.String(), "AppTemplateSpec", "AppTemplateSpec", 1), `&`, ``, 1) + `,`,
		`ValuesSchema:` + strings.Replace(strings.Replace(this.ValuesSchema.String(), "ValuesSchema", "ValuesSchema", 1), `&`, ``, 1) + `,`,
		`IncludedSoftware:` + repeatedStringForIncludedSoftware + `,`,
		`KappControllerVersionSelection:` + strings.Replace(this.KappControllerVersionSelection.String(), "VersionSelection", "VersionSelection", 1) + `,`,
		`KubernetesVersionSelection:` + strings.Replace(this.KubernetesVersionSelection.String(), "VersionSelection", "VersionSelection", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ValuesSchema) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ValuesSchema{`,
		`OpenAPIv3:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.OpenAPIv3), "RawExtension", "runtime.RawExtension", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VersionSelection) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VersionSelection{`,
		`Constraints:` + fmt.Sprintf("%v", this.Constraints) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *AppTemplateSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppTemplateSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppTemplateSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Spec == nil {
				m.Spec = &v1alpha1.AppSpec{}
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IncludedSoftware) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IncludedSoftware: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IncludedSoftware: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Maintainer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Maintainer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Maintainer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Package) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Package: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Package: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, Package{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageMetadataList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageMetadataList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageMetadataList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, PackageMetadata{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageMetadataSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageMetadataSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageMetadataSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LongDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LongDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShortDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShortDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IconSVGBase64", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IconSVGBase64 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maintainers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Maintainers = append(m.Maintainers, Maintainer{})
			if err := m.Maintainers[len(m.Maintainers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Categories", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Categories = append(m.Categories, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Licenses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Licenses = append(m.Licenses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleasedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReleasedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapactiyRequirementsDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CapactiyRequirementsDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseNotes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReleaseNotes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Template", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Template.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValuesSchema", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValuesSchema.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncludedSoftware", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncludedSoftware = append(m.IncludedSoftware, IncludedSoftware{})
			if err := m.IncludedSoftware[len(m.IncludedSoftware)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KappControllerVersionSelection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.KappControllerVersionSelection == nil {
				m.KappControllerVersionSelection = &VersionSelection{}
			}
			if err := m.KappControllerVersionSelection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KubernetesVersionSelection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.KubernetesVersionSelection == nil {
				m.KubernetesVersionSelection = &VersionSelection{}
			}
			if err := m.KubernetesVersionSelection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValuesSchema) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValuesSchema: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValuesSchema: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenAPIv3", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OpenAPIv3.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VersionSelection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionSelection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionSelection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constraints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Constraints = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
