//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	kappctrlv1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl/v1alpha1"
	datapackaging "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/apis/datapackaging"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AppTemplateSpec)(nil), (*datapackaging.AppTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateSpec_To_datapackaging_AppTemplateSpec(a.(*AppTemplateSpec), b.(*datapackaging.AppTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.AppTemplateSpec)(nil), (*AppTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_AppTemplateSpec_To_v1alpha1_AppTemplateSpec(a.(*datapackaging.AppTemplateSpec), b.(*AppTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IncludedSoftware)(nil), (*datapackaging.IncludedSoftware)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IncludedSoftware_To_datapackaging_IncludedSoftware(a.(*IncludedSoftware), b.(*datapackaging.IncludedSoftware), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.IncludedSoftware)(nil), (*IncludedSoftware)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_IncludedSoftware_To_v1alpha1_IncludedSoftware(a.(*datapackaging.IncludedSoftware), b.(*IncludedSoftware), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Maintainer)(nil), (*datapackaging.Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Maintainer_To_datapackaging_Maintainer(a.(*Maintainer), b.(*datapackaging.Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.Maintainer)(nil), (*Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_Maintainer_To_v1alpha1_Maintainer(a.(*datapackaging.Maintainer), b.(*Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Package)(nil), (*datapackaging.Package)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Package_To_datapackaging_Package(a.(*Package), b.(*datapackaging.Package), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.Package)(nil), (*Package)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_Package_To_v1alpha1_Package(a.(*datapackaging.Package), b.(*Package), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageList)(nil), (*datapackaging.PackageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageList_To_datapackaging_PackageList(a.(*PackageList), b.(*datapackaging.PackageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.PackageList)(nil), (*PackageList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_PackageList_To_v1alpha1_PackageList(a.(*datapackaging.PackageList), b.(*PackageList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageMetadata)(nil), (*datapackaging.PackageMetadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageMetadata_To_datapackaging_PackageMetadata(a.(*PackageMetadata), b.(*datapackaging.PackageMetadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.PackageMetadata)(nil), (*PackageMetadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_PackageMetadata_To_v1alpha1_PackageMetadata(a.(*datapackaging.PackageMetadata), b.(*PackageMetadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageMetadataList)(nil), (*datapackaging.PackageMetadataList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageMetadataList_To_datapackaging_PackageMetadataList(a.(*PackageMetadataList), b.(*datapackaging.PackageMetadataList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.PackageMetadataList)(nil), (*PackageMetadataList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_PackageMetadataList_To_v1alpha1_PackageMetadataList(a.(*datapackaging.PackageMetadataList), b.(*PackageMetadataList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageMetadataSpec)(nil), (*datapackaging.PackageMetadataSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageMetadataSpec_To_datapackaging_PackageMetadataSpec(a.(*PackageMetadataSpec), b.(*datapackaging.PackageMetadataSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.PackageMetadataSpec)(nil), (*PackageMetadataSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_PackageMetadataSpec_To_v1alpha1_PackageMetadataSpec(a.(*datapackaging.PackageMetadataSpec), b.(*PackageMetadataSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageSpec)(nil), (*datapackaging.PackageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageSpec_To_datapackaging_PackageSpec(a.(*PackageSpec), b.(*datapackaging.PackageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.PackageSpec)(nil), (*PackageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_PackageSpec_To_v1alpha1_PackageSpec(a.(*datapackaging.PackageSpec), b.(*PackageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Revoked)(nil), (*datapackaging.Revoked)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Revoked_To_datapackaging_Revoked(a.(*Revoked), b.(*datapackaging.Revoked), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.Revoked)(nil), (*Revoked)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_Revoked_To_v1alpha1_Revoked(a.(*datapackaging.Revoked), b.(*Revoked), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValuesSchema)(nil), (*datapackaging.ValuesSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValuesSchema_To_datapackaging_ValuesSchema(a.(*ValuesSchema), b.(*datapackaging.ValuesSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*datapackaging.ValuesSchema)(nil), (*ValuesSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_datapackaging_ValuesSchema_To_v1alpha1_ValuesSchema(a.(*datapackaging.ValuesSchema), b.(*ValuesSchema), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AppTemplateSpec_To_datapackaging_AppTemplateSpec(in *AppTemplateSpec, out *datapackaging.AppTemplateSpec, s conversion.Scope) error {
	out.Spec = (*kappctrlv1alpha1.AppSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v1alpha1_AppTemplateSpec_To_datapackaging_AppTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateSpec_To_datapackaging_AppTemplateSpec(in *AppTemplateSpec, out *datapackaging.AppTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateSpec_To_datapackaging_AppTemplateSpec(in, out, s)
}

func autoConvert_datapackaging_AppTemplateSpec_To_v1alpha1_AppTemplateSpec(in *datapackaging.AppTemplateSpec, out *AppTemplateSpec, s conversion.Scope) error {
	out.Spec = (*kappctrlv1alpha1.AppSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_datapackaging_AppTemplateSpec_To_v1alpha1_AppTemplateSpec is an autogenerated conversion function.
func Convert_datapackaging_AppTemplateSpec_To_v1alpha1_AppTemplateSpec(in *datapackaging.AppTemplateSpec, out *AppTemplateSpec, s conversion.Scope) error {
	return autoConvert_datapackaging_AppTemplateSpec_To_v1alpha1_AppTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_IncludedSoftware_To_datapackaging_IncludedSoftware(in *IncludedSoftware, out *datapackaging.IncludedSoftware, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Version = in.Version
	out.Description = in.Description
	return nil
}

// Convert_v1alpha1_IncludedSoftware_To_datapackaging_IncludedSoftware is an autogenerated conversion function.
func Convert_v1alpha1_IncludedSoftware_To_datapackaging_IncludedSoftware(in *IncludedSoftware, out *datapackaging.IncludedSoftware, s conversion.Scope) error {
	return autoConvert_v1alpha1_IncludedSoftware_To_datapackaging_IncludedSoftware(in, out, s)
}

func autoConvert_datapackaging_IncludedSoftware_To_v1alpha1_IncludedSoftware(in *datapackaging.IncludedSoftware, out *IncludedSoftware, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Version = in.Version
	out.Description = in.Description
	return nil
}

// Convert_datapackaging_IncludedSoftware_To_v1alpha1_IncludedSoftware is an autogenerated conversion function.
func Convert_datapackaging_IncludedSoftware_To_v1alpha1_IncludedSoftware(in *datapackaging.IncludedSoftware, out *IncludedSoftware, s conversion.Scope) error {
	return autoConvert_datapackaging_IncludedSoftware_To_v1alpha1_IncludedSoftware(in, out, s)
}

func autoConvert_v1alpha1_Maintainer_To_datapackaging_Maintainer(in *Maintainer, out *datapackaging.Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_Maintainer_To_datapackaging_Maintainer is an autogenerated conversion function.
func Convert_v1alpha1_Maintainer_To_datapackaging_Maintainer(in *Maintainer, out *datapackaging.Maintainer, s conversion.Scope) error {
	return autoConvert_v1alpha1_Maintainer_To_datapackaging_Maintainer(in, out, s)
}

func autoConvert_datapackaging_Maintainer_To_v1alpha1_Maintainer(in *datapackaging.Maintainer, out *Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_datapackaging_Maintainer_To_v1alpha1_Maintainer is an autogenerated conversion function.
func Convert_datapackaging_Maintainer_To_v1alpha1_Maintainer(in *datapackaging.Maintainer, out *Maintainer, s conversion.Scope) error {
	return autoConvert_datapackaging_Maintainer_To_v1alpha1_Maintainer(in, out, s)
}

func autoConvert_v1alpha1_Package_To_datapackaging_Package(in *Package, out *datapackaging.Package, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PackageSpec_To_datapackaging_PackageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Package_To_datapackaging_Package is an autogenerated conversion function.
func Convert_v1alpha1_Package_To_datapackaging_Package(in *Package, out *datapackaging.Package, s conversion.Scope) error {
	return autoConvert_v1alpha1_Package_To_datapackaging_Package(in, out, s)
}

func autoConvert_datapackaging_Package_To_v1alpha1_Package(in *datapackaging.Package, out *Package, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_datapackaging_PackageSpec_To_v1alpha1_PackageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_datapackaging_Package_To_v1alpha1_Package is an autogenerated conversion function.
func Convert_datapackaging_Package_To_v1alpha1_Package(in *datapackaging.Package, out *Package, s conversion.Scope) error {
	return autoConvert_datapackaging_Package_To_v1alpha1_Package(in, out, s)
}

func autoConvert_v1alpha1_PackageList_To_datapackaging_PackageList(in *PackageList, out *datapackaging.PackageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]datapackaging.Package)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PackageList_To_datapackaging_PackageList is an autogenerated conversion function.
func Convert_v1alpha1_PackageList_To_datapackaging_PackageList(in *PackageList, out *datapackaging.PackageList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageList_To_datapackaging_PackageList(in, out, s)
}

func autoConvert_datapackaging_PackageList_To_v1alpha1_PackageList(in *datapackaging.PackageList, out *PackageList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Package)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_datapackaging_PackageList_To_v1alpha1_PackageList is an autogenerated conversion function.
func Convert_datapackaging_PackageList_To_v1alpha1_PackageList(in *datapackaging.PackageList, out *PackageList, s conversion.Scope) error {
	return autoConvert_datapackaging_PackageList_To_v1alpha1_PackageList(in, out, s)
}

func autoConvert_v1alpha1_PackageMetadata_To_datapackaging_PackageMetadata(in *PackageMetadata, out *datapackaging.PackageMetadata, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PackageMetadataSpec_To_datapackaging_PackageMetadataSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PackageMetadata_To_datapackaging_PackageMetadata is an autogenerated conversion function.
func Convert_v1alpha1_PackageMetadata_To_datapackaging_PackageMetadata(in *PackageMetadata, out *datapackaging.PackageMetadata, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageMetadata_To_datapackaging_PackageMetadata(in, out, s)
}

func autoConvert_datapackaging_PackageMetadata_To_v1alpha1_PackageMetadata(in *datapackaging.PackageMetadata, out *PackageMetadata, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_datapackaging_PackageMetadataSpec_To_v1alpha1_PackageMetadataSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_datapackaging_PackageMetadata_To_v1alpha1_PackageMetadata is an autogenerated conversion function.
func Convert_datapackaging_PackageMetadata_To_v1alpha1_PackageMetadata(in *datapackaging.PackageMetadata, out *PackageMetadata, s conversion.Scope) error {
	return autoConvert_datapackaging_PackageMetadata_To_v1alpha1_PackageMetadata(in, out, s)
}

func autoConvert_v1alpha1_PackageMetadataList_To_datapackaging_PackageMetadataList(in *PackageMetadataList, out *datapackaging.PackageMetadataList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]datapackaging.PackageMetadata)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PackageMetadataList_To_datapackaging_PackageMetadataList is an autogenerated conversion function.
func Convert_v1alpha1_PackageMetadataList_To_datapackaging_PackageMetadataList(in *PackageMetadataList, out *datapackaging.PackageMetadataList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageMetadataList_To_datapackaging_PackageMetadataList(in, out, s)
}

func autoConvert_datapackaging_PackageMetadataList_To_v1alpha1_PackageMetadataList(in *datapackaging.PackageMetadataList, out *PackageMetadataList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PackageMetadata)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_datapackaging_PackageMetadataList_To_v1alpha1_PackageMetadataList is an autogenerated conversion function.
func Convert_datapackaging_PackageMetadataList_To_v1alpha1_PackageMetadataList(in *datapackaging.PackageMetadataList, out *PackageMetadataList, s conversion.Scope) error {
	return autoConvert_datapackaging_PackageMetadataList_To_v1alpha1_PackageMetadataList(in, out, s)
}

func autoConvert_v1alpha1_PackageMetadataSpec_To_datapackaging_PackageMetadataSpec(in *PackageMetadataSpec, out *datapackaging.PackageMetadataSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.LongDescription = in.LongDescription
	out.ShortDescription = in.ShortDescription
	out.IconSVGBase64 = in.IconSVGBase64
	out.ProviderName = in.ProviderName
	out.Maintainers = *(*[]datapackaging.Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.Categories = *(*[]string)(unsafe.Pointer(&in.Categories))
	out.SupportDescription = in.SupportDescription
	return nil
}

// Convert_v1alpha1_PackageMetadataSpec_To_datapackaging_PackageMetadataSpec is an autogenerated conversion function.
func Convert_v1alpha1_PackageMetadataSpec_To_datapackaging_PackageMetadataSpec(in *PackageMetadataSpec, out *datapackaging.PackageMetadataSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageMetadataSpec_To_datapackaging_PackageMetadataSpec(in, out, s)
}

func autoConvert_datapackaging_PackageMetadataSpec_To_v1alpha1_PackageMetadataSpec(in *datapackaging.PackageMetadataSpec, out *PackageMetadataSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.LongDescription = in.LongDescription
	out.ShortDescription = in.ShortDescription
	out.IconSVGBase64 = in.IconSVGBase64
	out.ProviderName = in.ProviderName
	out.Maintainers = *(*[]Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.Categories = *(*[]string)(unsafe.Pointer(&in.Categories))
	out.SupportDescription = in.SupportDescription
	return nil
}

// Convert_datapackaging_PackageMetadataSpec_To_v1alpha1_PackageMetadataSpec is an autogenerated conversion function.
func Convert_datapackaging_PackageMetadataSpec_To_v1alpha1_PackageMetadataSpec(in *datapackaging.PackageMetadataSpec, out *PackageMetadataSpec, s conversion.Scope) error {
	return autoConvert_datapackaging_PackageMetadataSpec_To_v1alpha1_PackageMetadataSpec(in, out, s)
}

func autoConvert_v1alpha1_PackageSpec_To_datapackaging_PackageSpec(in *PackageSpec, out *datapackaging.PackageSpec, s conversion.Scope) error {
	out.RefName = in.RefName
	out.Version = in.Version
	out.Licenses = *(*[]string)(unsafe.Pointer(&in.Licenses))
	out.ReleasedAt = in.ReleasedAt
	out.CapactiyRequirementsDescription = in.CapactiyRequirementsDescription
	out.ReleaseNotes = in.ReleaseNotes
	if err := Convert_v1alpha1_AppTemplateSpec_To_datapackaging_AppTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ValuesSchema_To_datapackaging_ValuesSchema(&in.ValuesSchema, &out.ValuesSchema, s); err != nil {
		return err
	}
	out.IncludedSoftware = *(*[]datapackaging.IncludedSoftware)(unsafe.Pointer(&in.IncludedSoftware))
	if err := Convert_v1alpha1_Revoked_To_datapackaging_Revoked(&in.Revoked, &out.Revoked, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PackageSpec_To_datapackaging_PackageSpec is an autogenerated conversion function.
func Convert_v1alpha1_PackageSpec_To_datapackaging_PackageSpec(in *PackageSpec, out *datapackaging.PackageSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageSpec_To_datapackaging_PackageSpec(in, out, s)
}

func autoConvert_datapackaging_PackageSpec_To_v1alpha1_PackageSpec(in *datapackaging.PackageSpec, out *PackageSpec, s conversion.Scope) error {
	out.RefName = in.RefName
	out.Version = in.Version
	out.Licenses = *(*[]string)(unsafe.Pointer(&in.Licenses))
	out.ReleasedAt = in.ReleasedAt
	out.CapactiyRequirementsDescription = in.CapactiyRequirementsDescription
	out.ReleaseNotes = in.ReleaseNotes
	if err := Convert_datapackaging_AppTemplateSpec_To_v1alpha1_AppTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	if err := Convert_datapackaging_ValuesSchema_To_v1alpha1_ValuesSchema(&in.ValuesSchema, &out.ValuesSchema, s); err != nil {
		return err
	}
	out.IncludedSoftware = *(*[]IncludedSoftware)(unsafe.Pointer(&in.IncludedSoftware))
	if err := Convert_datapackaging_Revoked_To_v1alpha1_Revoked(&in.Revoked, &out.Revoked, s); err != nil {
		return err
	}
	return nil
}

// Convert_datapackaging_PackageSpec_To_v1alpha1_PackageSpec is an autogenerated conversion function.
func Convert_datapackaging_PackageSpec_To_v1alpha1_PackageSpec(in *datapackaging.PackageSpec, out *PackageSpec, s conversion.Scope) error {
	return autoConvert_datapackaging_PackageSpec_To_v1alpha1_PackageSpec(in, out, s)
}

func autoConvert_v1alpha1_Revoked_To_datapackaging_Revoked(in *Revoked, out *datapackaging.Revoked, s conversion.Scope) error {
	out.Reason = in.Reason
	return nil
}

// Convert_v1alpha1_Revoked_To_datapackaging_Revoked is an autogenerated conversion function.
func Convert_v1alpha1_Revoked_To_datapackaging_Revoked(in *Revoked, out *datapackaging.Revoked, s conversion.Scope) error {
	return autoConvert_v1alpha1_Revoked_To_datapackaging_Revoked(in, out, s)
}

func autoConvert_datapackaging_Revoked_To_v1alpha1_Revoked(in *datapackaging.Revoked, out *Revoked, s conversion.Scope) error {
	out.Reason = in.Reason
	return nil
}

// Convert_datapackaging_Revoked_To_v1alpha1_Revoked is an autogenerated conversion function.
func Convert_datapackaging_Revoked_To_v1alpha1_Revoked(in *datapackaging.Revoked, out *Revoked, s conversion.Scope) error {
	return autoConvert_datapackaging_Revoked_To_v1alpha1_Revoked(in, out, s)
}

func autoConvert_v1alpha1_ValuesSchema_To_datapackaging_ValuesSchema(in *ValuesSchema, out *datapackaging.ValuesSchema, s conversion.Scope) error {
	out.OpenAPIv3 = in.OpenAPIv3
	return nil
}

// Convert_v1alpha1_ValuesSchema_To_datapackaging_ValuesSchema is an autogenerated conversion function.
func Convert_v1alpha1_ValuesSchema_To_datapackaging_ValuesSchema(in *ValuesSchema, out *datapackaging.ValuesSchema, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValuesSchema_To_datapackaging_ValuesSchema(in, out, s)
}

func autoConvert_datapackaging_ValuesSchema_To_v1alpha1_ValuesSchema(in *datapackaging.ValuesSchema, out *ValuesSchema, s conversion.Scope) error {
	out.OpenAPIv3 = in.OpenAPIv3
	return nil
}

// Convert_datapackaging_ValuesSchema_To_v1alpha1_ValuesSchema is an autogenerated conversion function.
func Convert_datapackaging_ValuesSchema_To_v1alpha1_ValuesSchema(in *datapackaging.ValuesSchema, out *ValuesSchema, s conversion.Scope) error {
	return autoConvert_datapackaging_ValuesSchema_To_v1alpha1_ValuesSchema(in, out, s)
}
