//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppTemplateSpec) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.AppTemplateSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IncludedSoftware) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.IncludedSoftware"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Maintainer) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.Maintainer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Package) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.Package"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageList) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageMetadata) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageMetadata"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageMetadataList) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageMetadataList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageMetadataSpec) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageMetadataSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PackageSpec) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.PackageSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ValuesSchema) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.ValuesSchema"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VersionSelection) OpenAPIModelName() string {
	return "dev.carvel.kapp-controller.pkg.apiserver.apis.datapackaging.v1alpha1.VersionSelection"
}
