apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: package-repository.example.com
  # Adds it to global namespace (as defined by kapp-controller)
  # which makes packages available in all namespaces
  namespace: kapp-controller-packaging-global
spec:
  fetch:
    imgpkgBundle:
      image: kind-registry.local:5000/package-repository:0.1.0
