// Code generated by main. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePackageMetadatas implements PackageMetadataInterface
type FakePackageMetadatas struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var packagemetadatasResource = schema.GroupVersionResource{Group: "data.packaging.carvel.dev", Version: "v1alpha1", Resource: "packagemetadatas"}

var packagemetadatasKind = schema.GroupVersionKind{Group: "data.packaging.carvel.dev", Version: "v1alpha1", Kind: "PackageMetadata"}

// Get takes name of the foo_PackageMetadata, and returns the corresponding foo_PackageMetadata object, and an error if there is any.
func (c *FakePackageMetadatas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PackageMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(packagemetadatasResource, c.ns, name), &v1alpha1.PackageMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PackageMetadata), err
}

// List takes label and field selectors, and returns the list of PackageMetadatas that match those selectors.
func (c *FakePackageMetadatas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PackageMetadataList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(packagemetadatasResource, packagemetadatasKind, c.ns, opts), &v1alpha1.PackageMetadataList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PackageMetadataList{ListMeta: obj.(*v1alpha1.PackageMetadataList).ListMeta}
	for _, item := range obj.(*v1alpha1.PackageMetadataList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested packageMetadatas.
func (c *FakePackageMetadatas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(packagemetadatasResource, c.ns, opts))

}

// Create takes the representation of a foo_PackageMetadata and creates it.  Returns the server's representation of the foo_PackageMetadata, and an error, if there is any.
func (c *FakePackageMetadatas) Create(ctx context.Context, foo_PackageMetadata *v1alpha1.PackageMetadata, opts v1.CreateOptions) (result *v1alpha1.PackageMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(packagemetadatasResource, c.ns, foo_PackageMetadata), &v1alpha1.PackageMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PackageMetadata), err
}

// Update takes the representation of a foo_PackageMetadata and updates it. Returns the server's representation of the foo_PackageMetadata, and an error, if there is any.
func (c *FakePackageMetadatas) Update(ctx context.Context, foo_PackageMetadata *v1alpha1.PackageMetadata, opts v1.UpdateOptions) (result *v1alpha1.PackageMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(packagemetadatasResource, c.ns, foo_PackageMetadata), &v1alpha1.PackageMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PackageMetadata), err
}

// Delete takes name of the foo_PackageMetadata and deletes it. Returns an error if one occurs.
func (c *FakePackageMetadatas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(packagemetadatasResource, c.ns, name), &v1alpha1.PackageMetadata{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePackageMetadatas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(packagemetadatasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PackageMetadataList{})
	return err
}

// Patch applies the patch and returns the patched foo_PackageMetadata.
func (c *FakePackageMetadatas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PackageMetadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(packagemetadatasResource, c.ns, name, pt, data, subresources...), &v1alpha1.PackageMetadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PackageMetadata), err
}
