// Code generated by main. DO NOT EDIT.

package fake

import (
	v1alpha1 "carvel.dev/kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	datapackagingv1alpha1 "carvel.dev/kapp-controller/pkg/apiserver/client/clientset/versioned/typed/datapackaging/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePackageMetadatas implements PackageMetadataInterface
type fakePackageMetadatas struct {
	*gentype.FakeClientWithList[*v1alpha1.PackageMetadata, *v1alpha1.PackageMetadataList]
	Fake *FakeDataV1alpha1
}

func newFakePackageMetadatas(fake *FakeDataV1alpha1, namespace string) datapackagingv1alpha1.PackageMetadataInterface {
	return &fakePackageMetadatas{
		gentype.NewFakeClientWithList[*v1alpha1.PackageMetadata, *v1alpha1.PackageMetadataList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("packagemetadatas"),
			v1alpha1.SchemeGroupVersion.WithKind("PackageMetadata"),
			func() *v1alpha1.PackageMetadata { return &v1alpha1.PackageMetadata{} },
			func() *v1alpha1.PackageMetadataList { return &v1alpha1.PackageMetadataList{} },
			func(dst, src *v1alpha1.PackageMetadataList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PackageMetadataList) []*v1alpha1.PackageMetadata {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PackageMetadataList, items []*v1alpha1.PackageMetadata) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
