// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/apis/packages/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PackageVersionLister helps list PackageVersions.
// All objects returned here must be treated as read-only.
type PackageVersionLister interface {
	// List lists all PackageVersions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PackageVersion, err error)
	// Get retrieves the PackageVersion from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.PackageVersion, error)
	PackageVersionListerExpansion
}

// packageVersionLister implements the PackageVersionLister interface.
type packageVersionLister struct {
	indexer cache.Indexer
}

// NewPackageVersionLister returns a new PackageVersionLister.
func NewPackageVersionLister(indexer cache.Indexer) PackageVersionLister {
	return &packageVersionLister{indexer: indexer}
}

// List lists all PackageVersions in the indexer.
func (s *packageVersionLister) List(selector labels.Selector) (ret []*v1alpha1.PackageVersion, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PackageVersion))
	})
	return ret, err
}

// Get retrieves the PackageVersion from the index for a given name.
func (s *packageVersionLister) Get(name string) (*v1alpha1.PackageVersion, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("packageversion"), name)
	}
	return obj.(*v1alpha1.PackageVersion), nil
}
