---
apiVersion: v1
kind: Namespace
metadata:
  name: kapp-controller
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.kappctrl.k14s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.friendlyDescription
    description: Friendly description
    name: Description
    type: string
  - JSONPath: .status.deploy.startedAt
    description: Last time app started being deployed. Does not mean anything was changed.
    name: Since-Deploy
    type: date
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created.
      It is not guaranteed to be set in happens-before order across separate operations.
      Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists.
      More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: kappctrl.k14s.io
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: packages.package.carvel.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.publicName
    description: Package public name
    name: Public-Name
    type: string
  - JSONPath: .spec.version
    description: Package version
    name: Version
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Time since creation
    name: Age
    type: date
  group: package.carvel.dev
  names:
    kind: Package
    listKind: PackageList
    plural: packages
    shortNames:
    - pkg
    singular: package
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: packagerepositories.install.package.carvel.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: Time since creation
    name: Age
    type: date
  group: install.package.carvel.dev
  names:
    kind: PackageRepository
    listKind: PackageRepositoryList
    plural: packagerepositories
    shortNames:
    - pkgr
    singular: packagerepository
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installedpackages.install.package.carvel.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.packageRef.publicName
    description: Package public name
    name: Package name
    type: string
  - JSONPath: .status.version
    description: Package version
    name: Package version
    type: string
  - JSONPath: .status.friendlyDescription
    description: Friendly description
    name: Description
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Time since creation
    name: Age
    type: date
  group: install.package.carvel.dev
  names:
    kind: InstalledPackage
    listKind: InstalledPackageList
    plural: installedpackages
    shortNames:
    - ipkg
    singular: installedpackage
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Path: /Users/embp/go/src/github.com/vmware-tanzu/carvel-kapp-controller
          Type: local
        - Dirty: true
          RemoteURL: git@github.com:vmware-tanzu/carvel-kapp-controller.git
          SHA: e6755bba67e2d176698f198eb22efd8430dfc4b3
          Type: git
        URL: index.docker.io/k8slt/kapp-controller@sha256:4c1433f8b0fbc0f49819d4703edd196f2f0a99907254b2291a8776b1c3665c98
  name: kapp-controller
  namespace: kapp-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kapp-controller
  template:
    metadata:
      labels:
        app: kapp-controller
    spec:
      containers:
      - args: []
        env:
        - name: KAPPCTRL_MEM_TMP_DIR
          value: /etc/kappctrl-mem-tmp
        image: index.docker.io/k8slt/kapp-controller@sha256:4c1433f8b0fbc0f49819d4703edd196f2f0a99907254b2291a8776b1c3665c98
        name: kapp-controller
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        securityContext:
          runAsGroup: 2000
          runAsUser: 1000
        volumeMounts:
        - mountPath: /etc/kappctrl-mem-tmp
          name: template-fs
      securityContext:
        fsGroup: 3000
      serviceAccount: kapp-controller-sa
      volumes:
      - emptyDir:
          medium: Memory
        name: template-fs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-controller-sa
  namespace: kapp-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapp-controller-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - secrets
  - configmaps
  verbs:
  - get
- apiGroups:
  - kappctrl.k14s.io
  resources:
  - apps
  - apps/status
  verbs:
  - '*'
- apiGroups:
  - install.package.carvel.dev
  resources:
  - installedpackages
  - installedpackages/status
  verbs:
  - '*'
- apiGroups:
  - package.carvel.dev
  resources:
  - packages
  - packages/status
  verbs:
  - '*'
- apiGroups:
  - install.package.carvel.dev
  resources:
  - packagerepositories
  - packagerepositories/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapp-controller-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kapp-controller-cluster-role
subjects:
- kind: ServiceAccount
  name: kapp-controller-sa
  namespace: kapp-controller
