// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	packagingv1alpha1 "carvel.dev/kapp-controller/pkg/apis/packaging/v1alpha1"
	scheme "carvel.dev/kapp-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PackageRepositoriesGetter has a method to return a PackageRepositoryInterface.
// A group's client should implement this interface.
type PackageRepositoriesGetter interface {
	PackageRepositories(namespace string) PackageRepositoryInterface
}

// PackageRepositoryInterface has methods to work with PackageRepository resources.
type PackageRepositoryInterface interface {
	Create(ctx context.Context, packageRepository *packagingv1alpha1.PackageRepository, opts v1.CreateOptions) (*packagingv1alpha1.PackageRepository, error)
	Update(ctx context.Context, packageRepository *packagingv1alpha1.PackageRepository, opts v1.UpdateOptions) (*packagingv1alpha1.PackageRepository, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, packageRepository *packagingv1alpha1.PackageRepository, opts v1.UpdateOptions) (*packagingv1alpha1.PackageRepository, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*packagingv1alpha1.PackageRepository, error)
	List(ctx context.Context, opts v1.ListOptions) (*packagingv1alpha1.PackageRepositoryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *packagingv1alpha1.PackageRepository, err error)
	PackageRepositoryExpansion
}

// packageRepositories implements PackageRepositoryInterface
type packageRepositories struct {
	*gentype.ClientWithList[*packagingv1alpha1.PackageRepository, *packagingv1alpha1.PackageRepositoryList]
}

// newPackageRepositories returns a PackageRepositories
func newPackageRepositories(c *PackagingV1alpha1Client, namespace string) *packageRepositories {
	return &packageRepositories{
		gentype.NewClientWithList[*packagingv1alpha1.PackageRepository, *packagingv1alpha1.PackageRepositoryList](
			"packagerepositories",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *packagingv1alpha1.PackageRepository { return &packagingv1alpha1.PackageRepository{} },
			func() *packagingv1alpha1.PackageRepositoryList { return &packagingv1alpha1.PackageRepositoryList{} },
		),
	}
}
