#@ load("@ytt:data", "data")

apiVersion: v1
kind: ConfigMap
metadata:
  name: kapp-controller-config
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "kapp-controller.carvel.dev/config"
data:
  #! Must match the second cert in the cert chain in kapp-controller/test/e2e/assets/self-signed-https-server.yml
  caCerts: |
    -----BEGIN CERTIFICATE-----
    MIIEOTCCAqGgAwIBAgIQYTfhca0MX1nKIfJIww3rhTANBgkqhkiG9w0BAQsFADAm
    MQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkwHhcNMjEwMzE4
    MjA0NDU1WhcNMjIwMzE4MjA0NDU1WjAmMQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoT
    DUNsb3VkIEZvdW5kcnkwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDu
    LHxaoq0pqvaUCeCEdkj6mbuNj4/1AVmoiLB6IUQP+JwY+n608QaDMJ7v1BD7TqzB
    M+dPFQDkmXvS5eHKLYEYmUCnTALVhZjVDjdslpvFt9v0CQKopl/ZqBMt1kkqoD2v
    4kO7147QYARxkPJI9MuOHtU5VC9/o58dm3TFiICyd9S72L13KKFGAv3YNTEtuIah
    B9z+FGAn21KdjKUULZihpgQfJub2fT1R0MEqSO9duEyzV+IJRyNwCgwnBTx0mIda
    zk7KbFujrpVbpQKtQwDqYVX0cHLPRIsScXVtb0GtNx1+MLP2d1muwmtYPBZdgEo1
    1p3Wd2NkXovo97oN4aUUH1mXyJTgLHTpKdJPGpBzEiK654CBe7KLnCmfodYKpZIq
    Qbcfj2rMWI6piRbvwk+SzFaxRcqPUbsd1DcvSN/gaXliVmvWB9jmcWLRFFJIp/p2
    bXUl/BFjrBMdhtVzr5K0uTU9zw/CKZ+njUhK0ztvq1pvqutt8UNhLdGh1V0F7a8C
    AwEAAaNjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
    BBYEFJ5TPL1gI3UtvhWYzpkxxvUOtCJzMB8GA1UdIwQYMBaAFJ5TPL1gI3UtvhWY
    zpkxxvUOtCJzMA0GCSqGSIb3DQEBCwUAA4IBgQDWktHBp141SsGVWFh9kJ6m2+DL
    acrkKy6mZaYxheFzPoGuFgRXEJdqMxnrNJ+kNHKg7IaD9dCTnXuy24PJW/SeLkjj
    8uKCRXIe3wVpoA0odSm5q/G/va+msipNRUqya9YitKh+zdf+r/fIiBXpiJdphXzD
    nkR1kzm5meDIPdQ1StK6aGC5SK89sz0whP+Pkb7gi6X2XXvB71rTvpBSoIxXUDDY
    v9gsp4icJhB+lSkvRcyIwhpl8tZw628X84pOHxdct7b7PYncj7JnmW2yiuY4en5s
    J4JCgICDDZMpU08izqkWC0EpMHvUbTfkOeKfM6q+ZhAnGIkCFVZxMXYFE2iCfiV8
    EzjRNwHaYtJYKUxZVahooMFdBhIUMeDje4XisN2zxoBzw8RVQURP/H0tEV24hHGj
    6LBMNoo4hBM3NcS9tLtG8Y60LN/AKccHWABMM8f4WQ7lGrppCo4w1cYbvJ7DaQFm
    PF8LHb327aa++PgEkJF/UvHDgjQzd8Nio/hCxpU=
    -----END CERTIFICATE-----

  #! must match the value in proxy_test.go
  httpProxy: proxy-svc.proxy-server.svc.cluster.local:80

  #! Uncomment and fill in a value to test with https proxy
  #! httpsProxy: ""

  #! must match the value in proxy_test.go and service dns in test/e2e/assests/registry/registry.yml
  noProxy: github.com,docker.io,registry-svc.registry.svc.cluster.local

  #! second index (split on .) needs to match serverNamespace in http_test.go's skip tls test
  dangerousSkipTLSVerify: registry-svc.registry.svc.cluster.local
