#@ load("@ytt:data", "data")

apiVersion: v1
kind: Secret
metadata:
  name: kapp-controller-config
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "kapp-controller.carvel.dev/config"
stringData:
  #! Must match the second cert in the cert chain in kapp-controller/test/e2e/assets/self-signed-https-server.yml
  caCerts: |
    -----BEGIN CERTIFICATE-----
    MIIEaTCCAtGgAwIBAgIQMnHSoj2so3Ye4U0CepDOfTANBgkqhkiG9w0BAQsFADA9
    MQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkxFTATBgNVBAMT
    DGdlbmVyYXRlZC1jYTAgFw0yMjAzMjIxNjA4NDNaGA8yMTIyMDIyNjE2MDg0M1ow
    PTEMMAoGA1UEBhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MRUwEwYDVQQD
    EwxnZW5lcmF0ZWQtY2EwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDm
    1mAC3HRlZd7ZTlPPB2K5AxHl8luSGmRm4UnYXxxCaoKNJAfP9Fr/f7NOXSss/R02
    F9JKH9UIAOaxSvyGnQegbbpRkRwvgPt76TSMrvwq/Qvr+beocJXeIbgNXY18/SLe
    jDyMJezDhWcOYolXOWD6+pNzJ5QjenidO82LVKOtp9umHRMqZbaBhW0AbN9WwV1e
    YM+iU/l9Ql7H+meDAioGP/NSduHtyD6dtgfFGVxwKEoU0HmVwCMsgcU5DVbexk01
    SDFOHNv1adfKIB0NQNZZNuT45QV3En2jON79EP7QQQ3kcX65BRv+AWsP0TNoa8SI
    Tma097oFnoats7JpcGptcgCafaZq1suGs2Lcc004cCOvcquw6ow3hXw0YCKZHDNO
    TGPdylU8T3FTrB9gJMBrwCs7OqjCL83m6vr68vICswNch6jaVaTkiRheTfjUyShP
    GmUsCvv/yT5sBt6kjzlCTtGlSKDOYxEqoMbvsV34Cb1qUUjoalYKfsn3Fo6ttVMC
    AwEAAaNjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
    BBYEFOxC7vVMU3/CO7q9Ylp1zVL9AW2cMB8GA1UdIwQYMBaAFOxC7vVMU3/CO7q9
    Ylp1zVL9AW2cMA0GCSqGSIb3DQEBCwUAA4IBgQDICCkhON4+AIxHrbtK1rfuF7vK
    Ck1yL0k482H+FH1bkMXCTGTtBPsk9yvG0mGzSi6f52euh2m+ZKWp5MXRcPJT5OUC
    59oXZhLiHBeQRQ5cJRXxz7OgsGORwjWIrjU1mHq6xAIwl59v0QennCDHUFzu6nPw
    6dgy+excnZ4KJmH70D3/QRxfj2nuxe5KyobTyOQIawRl1TTgLSRMchiDp23TbIWe
    ZLiyb2CoWdRfQfEanwYbAavyhYNQJCWLwDExBYEV5Ep6hr1g5E8jHN6f+/0a5nkK
    GES8ooNXEsm9QTuA2Cnvf8a9jYoRAHrMoL0KlaP+0HikjFoySafl5UFdm/iEWVRV
    fmDRVhlZZ0bHX/0jR1woV/Nlz3dRysMH4M7/FKsuPFYg9xOfqa0PwBFNK0Os1jM7
    WM+DlzZxGMBd7QKW7xCdEuUmKxB8gQw0LvStYM/38MB5KMDtFo/uTIkr1HsEpSNG
    lYEKi+1KNYrJFl+DIUQVWoC+fi0Doiqor2D2Zkk=
    -----END CERTIFICATE-----

  #! must match the value in proxy_test.go
  httpProxy: proxy-svc.proxy-server.svc.cluster.local:80

  #! Uncomment and fill in a value to test with https proxy
  #! httpsProxy: ""

  #! must match the service dns in test/e2e/assests/registry/registry.yml
  noProxy: github.com,docker.io,registry-svc.registry.svc.cluster.local,KAPPCTRL_KUBERNETES_SERVICE_HOST

  #! second index (split on .) needs to match serverNamespace in http_test.go's skip tls test
  dangerousSkipTLSVerify: registry-svc.registry.svc.cluster.local
