apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: redis-enterprise-operator.carvel.dev.0.0.0
spec:
  refName: redis-enterprise-operator.carvel.dev
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - upstream
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: redis-enterprise-operator.carvel.dev
spec:
  displayName: redis-enterprise-operator
  longDescription: redis-enterprise-operator.carvel.dev
  shortDescription: redis-enterprise-operator.carvel.dev

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: redis-enterprise-operator
spec:
  packageRef:
    refName: redis-enterprise-operator.carvel.dev
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: redis-enterprise-operator-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
