run:
  timeout: 5m
linters:
  enable:
    - goheader
    - revive
    - deadcode
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 202[0-1]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new-from-rev: a2236fb3c56c014a8ca10ce422208e45d21229e1 # only enforce for commits after Jul 6 2021, allows us to phase-in godoc compliance
