run:
  timeout: 5m
version: "2"
linters:
  enable:
    - goheader
    - revive
    - unused
# all available settings of specific linters
  settings:
    goheader:
      values:
        regexp:
          copyright-year: 20[0-9][0-9]
      template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: 97995c030c948b44e4a79d3a94733f302d6ba6e9 # only enforce for commits after Nov 28 2025.
