linters:
  enable:
    - goheader
    - golint
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0