run:
  timeout: 5m
linters:
  enable:
    - goheader
    - revive
    - deadcode
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 20[0-9][0-9]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new-from-rev: c1a0a1445615c515f3b6f5006b857b8f426308ef # only enforce for commits after Jan 11 2022, allows us to phase-in godoc compliance
