apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: kapp-controller.carvel.dev
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - config
          - kbld:
              paths:
              - '-'
              - .imgpkg/images.yml
      export:
      - imgpkgBundle:
          image: ghcr.io/rcmadhankumar/kapp-controller-package-bundle
          useKbldImagesLock: false
        includePaths:
        - config
        - .imgpkg/images.yml
