apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: kapp-controller.carvel.dev
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - config
              - config-release
          - kbld:
              paths:
              - '-'
      export:
      - imgpkgBundle:
          image: ghcr.io/vmware-tanzu/carvel-kapp-controller
          useKbldImagesLock: true
        includePaths:
        - config
        - config-release