// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// InternalPackageMetadatas returns a InternalPackageMetadataInformer.
	InternalPackageMetadatas() InternalPackageMetadataInformer
	// InternalPackageVersions returns a InternalPackageVersionInformer.
	InternalPackageVersions() InternalPackageVersionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// InternalPackageMetadatas returns a InternalPackageMetadataInformer.
func (v *version) InternalPackageMetadatas() InternalPackageMetadataInformer {
	return &internalPackageMetadataInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// InternalPackageVersions returns a InternalPackageVersionInformer.
func (v *version) InternalPackageVersions() InternalPackageVersionInformer {
	return &internalPackageVersionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
