// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	internalpackagingv1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/internalpackaging/v1alpha1"
	versioned "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/listers/internalpackaging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InternalPackageVersionInformer provides access to a shared informer and lister for
// InternalPackageVersions.
type InternalPackageVersionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.InternalPackageVersionLister
}

type internalPackageVersionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInternalPackageVersionInformer constructs a new informer for InternalPackageVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInternalPackageVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInternalPackageVersionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInternalPackageVersionInformer constructs a new informer for InternalPackageVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInternalPackageVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalV1alpha1().InternalPackageVersions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalV1alpha1().InternalPackageVersions(namespace).Watch(context.TODO(), options)
			},
		},
		&internalpackagingv1alpha1.InternalPackageVersion{},
		resyncPeriod,
		indexers,
	)
}

func (f *internalPackageVersionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInternalPackageVersionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *internalPackageVersionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&internalpackagingv1alpha1.InternalPackageVersion{}, f.defaultInformer)
}

func (f *internalPackageVersionInformer) Lister() v1alpha1.InternalPackageVersionLister {
	return v1alpha1.NewInternalPackageVersionLister(f.Informer().GetIndexer())
}
