// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AppExpansion interface{}

type InstalledPkgExpansion interface{}

type PkgExpansion interface{}

type PkgRepositoryExpansion interface{}
