#@ load("@ytt:data", "data")

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: kapp-controller
  path: .
  docker:
    buildx:
      pull: true
      noCache: true
      #! pass kapp_controller_version into Dockerfile.
      rawOptions:
      - #@ "--build-arg=KCTRL_VER="+data.values.dev.version
      #@ if/end data.values.dev.platform != "":
      - #@ "--platform="+data.values.dev.platform
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
destinations:
- image: kapp-controller
  newImage: #@ data.values.dev.image_repo
