#@data/values-schema
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults
#@schema/desc "Configuration explicitly for developing secretgen-controller"
dev:
  #@schema/desc "Location of kapp-controller image"
  image_repo: "docker.io/ysethiya/carvel-kapp-controller"
  #@schema/desc "Development version"
  kapp_controller_version: develop
  #@schema/desc "Comma separated list of supported architectures"
  platform: "linux/amd64,linux/arm64"
  #@schema/desc "image push flag"
  push_images: "true"
  #@schema/desc "image cache flag"
  image_cache: false
  