---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: pkg2.test.carvel.dev.2.0.0
  # cluster scoped
spec:
  publicName: pkg2.test.carvel.dev
  # In this new version of the package, we are including some overlays
  # which will increase the pod count for the simple app.
  version: 2.0.0
  displayName: "Test Package in repo"
  description: "Package used for testing"
  template:
    spec:
      fetch:
      - image:
          url: ewrenn/pkg2:v2.0.0
      template:
      - ytt:
          paths:
          - config-step-2-template
          - config-step-2a-overlays
      deploy:
      - kapp: {}
