#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapp-controller
  namespace: #@ data.values.namespace
  annotations:
    kapp-controller.carvel.dev/version: v0.0.0
spec:
  selector:
    matchLabels:
      app: kapp-controller
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: kapp-controller
    spec:
      serviceAccount: kapp-controller-sa
      containers:
      - name: kapp-controller
        image: kapp-controller
        args:
        - #@ "-packaging-global-namespace={}".format(data.values.packagingGlobalNamespace)
        #@ if/end data.values.dangerousEnablePprof:
        - -dangerous-enable-pprof=true
        - #@ "-enable-api-priority-and-fairness={}".format(data.values.enableApiPriorityAndFairness)
        - #@ "-tls-cipher-suites={}".format(data.values.tlsCipherSuites)
        env:
        - name: KAPPCTRL_MEM_TMP_DIR
          value: /etc/kappctrl-mem-tmp
        - name: KAPPCTRL_SIDECAREXEC_SOCK
          value: /etc/kappctrl-mem-tmp/sidecarexec.sock
        - name: KAPPCTRL_SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KAPPCTRL_API_PORT
          value: #@ str(data.values.apiPort)
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        volumeMounts:
        - name: template-fs
          mountPath: /etc/kappctrl-mem-tmp
        - name: home
          mountPath: /home/kapp-controller
        ports:
        - containerPort: #@ data.values.apiPort
          name: api
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      - name: kapp-controller-sidecarexec
        image: kapp-controller
        args: ["--sidecarexec"]
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        env:
        - name: KAPPCTRL_SIDECAREXEC_SOCK
          value: /etc/kappctrl-mem-tmp/sidecarexec.sock
        - name: IMGPKG_ACTIVE_KEYCHAINS
          value: gke,aks,ecr
        volumeMounts:
        - name: template-fs
          mountPath: /etc/kappctrl-mem-tmp
        - name: home
          mountPath: /home/kapp-controller
        #! mount over service account token to make it not available
        - name: empty-sa
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false #! TODO(bmo): don't write to the root ca-bundle
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: template-fs
        emptyDir:
          medium: Memory
      - name: home
        emptyDir:
          medium: Memory
      - name: empty-sa
        emptyDir: {}

#@ if/end data.values.dangerousEnablePprof:
---
apiVersion: v1
kind: Service
metadata:
  name: pprof
  namespace: #@ data.values.namespace
spec:
  type: NodePort
  selector:
    app: kapp-controller
  ports:
  - port: 6060
    protocol: TCP
