---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: InstalledPkg
metadata:
  name: pkg-demo
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  pkgRef:
    publicName: pkg2.test.carvel.dev
    versionSelection: {}
  values:
  - secretRef:
      name: pkg-demo-values
---
apiVersion: v1
kind: Secret
metadata:
  name: pkg-demo-values
stringData:
  values.yml: |
    #@data/values
    ---
    hello_msg: "hi"
