---
apiVersion: install.package.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: package-demo
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    publicName: pkg2.test.carvel.dev
    versionSelection: {}
  values:
  - secretRef:
      name: package-demo-values
---
apiVersion: v1
kind: Secret
metadata:
  name: package-demo-values
stringData:
  values.yml: |
    #@data/values
    ---
    hello_msg: "hi"
