---
apiVersion: install.package.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: basic.test.carvel.dev
spec:
  # Here we are fetching a list of packages from a docker registry. This reference
  # points to an imgpkg bundle, which is our recommended way of storing a package
  # repository
  fetch:
    image:
      # This image was create by running `imgpkg push -i <repo> -f repo`. The resulting
      # image will contain the packages within the pkgs folder and, by adding this repo to the cluster,
      # those packages will also be available for installation.
      url: k8slt/kctrl-pkg-repo-bundle:v1.0.0
