// Code generated by main. DO NOT EDIT.

package v1alpha1

// PackageInstallListerExpansion allows custom methods to be added to
// PackageInstallLister.
type PackageInstallListerExpansion interface{}

// PackageInstallNamespaceListerExpansion allows custom methods to be added to
// PackageInstallNamespaceLister.
type PackageInstallNamespaceListerExpansion interface{}

// PackageRepositoryListerExpansion allows custom methods to be added to
// PackageRepositoryLister.
type PackageRepositoryListerExpansion interface{}

// PackageRepositoryNamespaceListerExpansion allows custom methods to be added to
// PackageRepositoryNamespaceLister.
type PackageRepositoryNamespaceListerExpansion interface{}
