// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// InstalledPackageListerExpansion allows custom methods to be added to
// InstalledPackageLister.
type InstalledPackageListerExpansion interface{}

// InstalledPackageNamespaceListerExpansion allows custom methods to be added to
// InstalledPackageNamespaceLister.
type InstalledPackageNamespaceListerExpansion interface{}

// PackageRepositoryListerExpansion allows custom methods to be added to
// PackageRepositoryLister.
type PackageRepositoryListerExpansion interface{}
