// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type InstalledPackageExpansion interface{}

type InternalPackageExpansion interface{}

type InternalPackageVersionExpansion interface{}

type PackageRepositoryExpansion interface{}
