// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/installpackage/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InstalledPackagesGetter has a method to return a InstalledPackageInterface.
// A group's client should implement this interface.
type InstalledPackagesGetter interface {
	InstalledPackages(namespace string) InstalledPackageInterface
}

// InstalledPackageInterface has methods to work with InstalledPackage resources.
type InstalledPackageInterface interface {
	Create(ctx context.Context, installedPackage *v1alpha1.InstalledPackage, opts v1.CreateOptions) (*v1alpha1.InstalledPackage, error)
	Update(ctx context.Context, installedPackage *v1alpha1.InstalledPackage, opts v1.UpdateOptions) (*v1alpha1.InstalledPackage, error)
	UpdateStatus(ctx context.Context, installedPackage *v1alpha1.InstalledPackage, opts v1.UpdateOptions) (*v1alpha1.InstalledPackage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InstalledPackage, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InstalledPackageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InstalledPackage, err error)
	InstalledPackageExpansion
}

// installedPackages implements InstalledPackageInterface
type installedPackages struct {
	client rest.Interface
	ns     string
}

// newInstalledPackages returns a InstalledPackages
func newInstalledPackages(c *InstallV1alpha1Client, namespace string) *installedPackages {
	return &installedPackages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the installedPackage, and returns the corresponding installedPackage object, and an error if there is any.
func (c *installedPackages) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InstalledPackage, err error) {
	result = &v1alpha1.InstalledPackage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("installedpackages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InstalledPackages that match those selectors.
func (c *installedPackages) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InstalledPackageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InstalledPackageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("installedpackages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested installedPackages.
func (c *installedPackages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("installedpackages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a installedPackage and creates it.  Returns the server's representation of the installedPackage, and an error, if there is any.
func (c *installedPackages) Create(ctx context.Context, installedPackage *v1alpha1.InstalledPackage, opts v1.CreateOptions) (result *v1alpha1.InstalledPackage, err error) {
	result = &v1alpha1.InstalledPackage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("installedpackages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(installedPackage).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a installedPackage and updates it. Returns the server's representation of the installedPackage, and an error, if there is any.
func (c *installedPackages) Update(ctx context.Context, installedPackage *v1alpha1.InstalledPackage, opts v1.UpdateOptions) (result *v1alpha1.InstalledPackage, err error) {
	result = &v1alpha1.InstalledPackage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("installedpackages").
		Name(installedPackage.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(installedPackage).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *installedPackages) UpdateStatus(ctx context.Context, installedPackage *v1alpha1.InstalledPackage, opts v1.UpdateOptions) (result *v1alpha1.InstalledPackage, err error) {
	result = &v1alpha1.InstalledPackage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("installedpackages").
		Name(installedPackage.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(installedPackage).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the installedPackage and deletes it. Returns an error if one occurs.
func (c *installedPackages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("installedpackages").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *installedPackages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("installedpackages").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched installedPackage.
func (c *installedPackages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InstalledPackage, err error) {
	result = &v1alpha1.InstalledPackage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("installedpackages").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
