#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name": "kapp-controller"}})
#@overlay/insert before=True
---
#! This optional Secret must be created before the kapp-controller pod launches in order to read it.
apiVersion: v1
kind: Secret
metadata:
  #! Name must be `kapp-controller-config` for kapp controller to pick it up
  name: kapp-controller-config
  namespace: #@ data.values.namespace
stringData: #@ data.values.config
