#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"metadata":{"name":"packagerepositories.packaging.carvel.dev"}})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    packaging.carvel.dev/global-namespace: #@ data.values.packagingGlobalNamespace
