---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  # This is just the resource name and shouldn't be used to reference this package
  # in other resources
  name: simple-app.corp.com
  # cluster scoped
spec:
  # This is the name we want to reference in resources such as PackageInstall.
  displayName: "simple-app"
  shortDescription: "Simple app consisting of a k8s deployment and service"
  longDescription: "A longer, more detailed description of what the package contains and what it is for"
  providerName: Carvel
  maintainers:
  - name: carvel
  categories:
  - testing
  supportDescription: "Description of support provided for the package"

