apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - git:
      url: https://github.com/k14s/k8s-simple-app-example
      ref: origin/develop
      subPath: config-step-2-template
  template:
  - ytt:
      inline:
        pathsFrom:
        - secretRef:
            name: simple-app-values
  deploy:
  - kapp: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-app-values
  namespace: default
stringData:
  values2.yml: |
    #@data/values
    ---
    hello_msg: updated
