{{- $watchNamespace := list .Release.Namespace }}
{{- if .Values.operator.watchNamespace }}
{{- $watchNamespace = regexSplit "," .Values.operator.watchNamespace -1 }}
{{- end }}


{{- range $idx, $namespace := $watchNamespace }}

{{- $namespaceBlock := printf "namespace: %s" $namespace }}
{{- if eq $namespace "*" }}
{{- $namespaceBlock = printf "namespace: %s" $.Release.Namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-appdb
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
- name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-database-pods
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-ops-manager
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
- name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  {{ $namespaceBlock }}
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - patch
  - delete
  - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  {{ $namespaceBlock }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-appdb
subjects:
- kind: ServiceAccount
  name: mongodb-enterprise-appdb
  {{ $namespaceBlock }}

{{- end }}
