{{ if .Values.operator.createOperatorServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.registry.imagePullSecrets}}
imagePullSecrets:
- name: {{ .Values.registry.imagePullSecrets }}
{{- end }}

{{- end }}

{{- $watchNamespace := list .Release.Namespace }}
{{- if .Values.operator.watchNamespace }}
{{- $watchNamespace = regexSplit "," .Values.operator.watchNamespace -1 }}
{{- $watchNamespace = concat $watchNamespace (list .Release.Namespace) }}
{{- end }}

{{- $roleScope := "Role" -}}
{{- if or (gt (len $watchNamespace) 1) (eq (first $watchNamespace) "*") }}
{{- $roleScope = "ClusterRole" }}
{{- end }}

---
kind: {{ $roleScope }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}
{{- if eq $roleScope "Role" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
rules:
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
  - deletecollection
- apiGroups:
  - mongodb.com
  verbs:
  - '*'
  resources:
  - mongodb
  - mongodb/finalizers
  - mongodbusers
  - opsmanagers
  - opsmanagers/finalizers
  - mongodbmulti
  - mongodbmulti/finalizers
{{- if .Values.subresourceEnabled }}
  - mongodb/status
  - mongodbusers/status
  - opsmanagers/status
  - mongodbmulti/status
{{- end }}
{{- if eq $roleScope "ClusterRole" }}
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - list
  - watch
{{- end}}

# This ClusterRoleBinding is necessary in order to use validating
# webhooks—these will prevent you from applying a variety of invalid resource
# definitions. The validating webhooks are optional so this can be removed if
# necessary.
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-{{ .Release.Namespace }}-webhook-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-enterprise-operator-mongodb-webhook
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}

{{- range $idx, $namespace := $watchNamespace }}

{{- $namespaceBlock := "" }}
{{- if not (eq $namespace "*") }}
{{- $namespaceBlock = printf "namespace: %s" $namespace }}
{{- end }}

---
{{- if eq $namespace "*" }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.operator.name }}
  {{ $namespaceBlock }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $roleScope }}
  name: {{ $.Values.operator.name }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.operator.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
