apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: dynatrace.carvel.dev
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - upstream
          - kbld: {}
      export:
      - imgpkgBundle:
          image: rohitagg2020/dynatrace-bundle
          useKbldImagesLock: true
        includePaths:
        - upstream
