// Code generated by main. DO NOT EDIT.

package fake

import (
	v1alpha1 "carvel.dev/kapp-controller/pkg/apis/packaging/v1alpha1"
	packagingv1alpha1 "carvel.dev/kapp-controller/pkg/client/clientset/versioned/typed/packaging/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePackageInstalls implements PackageInstallInterface
type fakePackageInstalls struct {
	*gentype.FakeClientWithList[*v1alpha1.PackageInstall, *v1alpha1.PackageInstallList]
	Fake *FakePackagingV1alpha1
}

func newFakePackageInstalls(fake *FakePackagingV1alpha1, namespace string) packagingv1alpha1.PackageInstallInterface {
	return &fakePackageInstalls{
		gentype.NewFakeClientWithList[*v1alpha1.PackageInstall, *v1alpha1.PackageInstallList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("packageinstalls"),
			v1alpha1.SchemeGroupVersion.WithKind("PackageInstall"),
			func() *v1alpha1.PackageInstall { return &v1alpha1.PackageInstall{} },
			func() *v1alpha1.PackageInstallList { return &v1alpha1.PackageInstallList{} },
			func(dst, src *v1alpha1.PackageInstallList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PackageInstallList) []*v1alpha1.PackageInstall {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PackageInstallList, items []*v1alpha1.PackageInstall) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
