// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// InternalPackageListerExpansion allows custom methods to be added to
// InternalPackageLister.
type InternalPackageListerExpansion interface{}

// InternalPackageVersionListerExpansion allows custom methods to be added to
// InternalPackageVersionLister.
type InternalPackageVersionListerExpansion interface{}
