// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// InternalPackageMetadataListerExpansion allows custom methods to be added to
// InternalPackageMetadataLister.
type InternalPackageMetadataListerExpansion interface{}

// InternalPackageMetadataNamespaceListerExpansion allows custom methods to be added to
// InternalPackageMetadataNamespaceLister.
type InternalPackageMetadataNamespaceListerExpansion interface{}

// InternalPackageVersionListerExpansion allows custom methods to be added to
// InternalPackageVersionLister.
type InternalPackageVersionListerExpansion interface{}

// InternalPackageVersionNamespaceListerExpansion allows custom methods to be added to
// InternalPackageVersionNamespaceLister.
type InternalPackageVersionNamespaceListerExpansion interface{}
