// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/installpackage/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInternalPackageVersions implements InternalPackageVersionInterface
type FakeInternalPackageVersions struct {
	Fake *FakeInstallV1alpha1
}

var internalpackageversionsResource = schema.GroupVersionResource{Group: "install.package.carvel.dev", Version: "v1alpha1", Resource: "internalpackageversions"}

var internalpackageversionsKind = schema.GroupVersionKind{Group: "install.package.carvel.dev", Version: "v1alpha1", Kind: "InternalPackageVersion"}

// Get takes name of the internalPackageVersion, and returns the corresponding internalPackageVersion object, and an error if there is any.
func (c *FakeInternalPackageVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InternalPackageVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(internalpackageversionsResource, name), &v1alpha1.InternalPackageVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InternalPackageVersion), err
}

// List takes label and field selectors, and returns the list of InternalPackageVersions that match those selectors.
func (c *FakeInternalPackageVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InternalPackageVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(internalpackageversionsResource, internalpackageversionsKind, opts), &v1alpha1.InternalPackageVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InternalPackageVersionList{ListMeta: obj.(*v1alpha1.InternalPackageVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.InternalPackageVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested internalPackageVersions.
func (c *FakeInternalPackageVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(internalpackageversionsResource, opts))
}

// Create takes the representation of a internalPackageVersion and creates it.  Returns the server's representation of the internalPackageVersion, and an error, if there is any.
func (c *FakeInternalPackageVersions) Create(ctx context.Context, internalPackageVersion *v1alpha1.InternalPackageVersion, opts v1.CreateOptions) (result *v1alpha1.InternalPackageVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(internalpackageversionsResource, internalPackageVersion), &v1alpha1.InternalPackageVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InternalPackageVersion), err
}

// Update takes the representation of a internalPackageVersion and updates it. Returns the server's representation of the internalPackageVersion, and an error, if there is any.
func (c *FakeInternalPackageVersions) Update(ctx context.Context, internalPackageVersion *v1alpha1.InternalPackageVersion, opts v1.UpdateOptions) (result *v1alpha1.InternalPackageVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(internalpackageversionsResource, internalPackageVersion), &v1alpha1.InternalPackageVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InternalPackageVersion), err
}

// Delete takes name of the internalPackageVersion and deletes it. Returns an error if one occurs.
func (c *FakeInternalPackageVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(internalpackageversionsResource, name), &v1alpha1.InternalPackageVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInternalPackageVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(internalpackageversionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InternalPackageVersionList{})
	return err
}

// Patch applies the patch and returns the patched internalPackageVersion.
func (c *FakeInternalPackageVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InternalPackageVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(internalpackageversionsResource, name, pt, data, subresources...), &v1alpha1.InternalPackageVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InternalPackageVersion), err
}
