---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: pkg-standalone.test.carvel.dev
  namespace: pkg-standalone
spec:
  displayName: "Test Package standalone"
  shortDescription: "Package used for testing"
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: pkg-standalone.test.carvel.dev.2.0.0
  namespace: pkg-standalone
spec:
  refName: pkg-standalone.test.carvel.dev
  version: 2.0.0
  releasedAt: 2021-05-05T18:57:06Z
  template: # type of App CR
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
      template:
      - ytt:
          paths:
          - config-step-2-template
          - config-step-2a-overlays
          inline:
            paths:
              remove-ns.yml: |
                #@ load("@ytt:overlay", "overlay")
                #@overlay/match by=overlay.all,expects="1+"
                ---
                metadata:
                  #@overlay/remove
                  namespace:
      deploy:
      - kapp: {}
