#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: kapp-controller
  path: .
  #@ def docker_rawOpts(): return ["--build-arg", "KCTRL_VER="+data.values.kapp_controller_version]
  #@ if/end not data.values.image_cache:
  docker:
    build:
      #! Always rebuild image
      pull: true
      noCache: true
      #! pass kapp_controller_version into Dockerfile.
      rawOptions: #@ docker_rawOpts()

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: kapp-controller
  newImage: #@ data.values.image_repo
