#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "CustomResourceDefinition"}), expects="0+"
---
metadata:
  #@overlay/remove
  #@overlay/match missing_ok=True
  creationTimestamp: null
  #@overlay/remove
  #@overlay/match missing_ok=True
  annotations:
spec:
  validation:
    openAPIV3Schema:
      properties:
        #@overlay/remove
        #@overlay/match missing_ok=True
        metadata:
#@overlay/remove
#@overlay/match missing_ok=True
status:
