apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.kappctrl.k14s.io
spec:
  group: kappctrl.k14s.io
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Description
    type: string
    description: Friendly description
    JSONPath: .status.friendlyDescription
  - name: Since-Deploy
    type: date
    description: Last time app started being deployed. Does not mean anything was changed.
    JSONPath: .status.deploy.startedAt
  - name: Age
    type: date
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created.
      It is not guaranteed to be set in happens-before order across separate operations.
      Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists.
      More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: packages.package.carvel.dev
spec:
  group: package.carvel.dev
  names:
    kind: Package
    listKind: PackageList
    plural: packages
    singular: package
    shortNames:
      - pkg
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Public-Name
    type: string
    description: Package public name
    JSONPath: .spec.publicName
  - name: Version
    type: string
    description: Package version
    JSONPath: .spec.version
  - name: Age
    type: date
    description: Time since creation
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: packagerepositories.install.package.carvel.dev
spec:
  group: install.package.carvel.dev
  names:
    kind: PackageRepository
    listKind: PackageRepositoryList
    plural: packagerepositories
    singular: packagerepository
    shortNames:
    - pkgr
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Age
    type: date
    description: Time since creation
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installedpackages.install.package.carvel.dev
spec:
  group: install.package.carvel.dev
  names:
    kind: InstalledPackage
    listKind: InstalledPackageList
    plural: installedpackages
    singular: installedpackage
    shortNames:
    - ipkg
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
  additionalPrinterColumns:
  #! TODO package name+version should be pointing at
  #! resolved information. for poc just point at pkgRef
  - name: Package name
    type: string
    description: Package public name
    JSONPath: .spec.packageRef.publicName
  - name: Package version
    type: string
    description: Package version
    JSONPath: .status.version
  - name: Description
    type: string
    description: Friendly description
    JSONPath: .status.friendlyDescription
  - name: Age
    type: date
    description: Time since creation
    JSONPath: .metadata.creationTimestamp
