---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: pkg1.test.carvel.dev
  # cluster scoped
spec:
  displayName: "Test Package"
  shortDescription: "Package used for testing"
---
apiVersion: package.carvel.dev/v1alpha1
kind: PackageVersion
metadata:
  name: pkg1.test.carvel.dev.2.0.0
spec:
  packageName: pkg1.test.carvel.dev
  version: 2.0.0
  template: # type of App CR
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
      template:
      - ytt:
          paths:
          - config-step-2-template
          - config-step-2a-overlays
      deploy:
      - kapp: {}
---
apiVersion: install.package.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: installed-pkg-test
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  packageName: pkg1.test.carvel.dev
  versionSelection:
    constraints: "2.0.0"
  values:
  - secretRef:
      name: simple-values
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-values
stringData:
  values.yml: |
    #@data/values
    ---
    hello_msg: "hi"
