---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: Pkg
metadata:
  name: pkg1.test.carvel.dev.v1.0
  # cluster scoped
spec:
  publicName: pkg1.test.carvel.dev
  version: v1.0.0
  displayName: "Test Package"
  description: "Package used for testing"
  template: # type of App CR
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
          subPath: config-step-2-template
      template:
      - ytt: {}
      deploy:
      - kapp: {}
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: Pkg
metadata:
  name: pkg1.test.carvel.dev.v2.0
  # cluster scoped
spec:
  publicName: pkg1.test.carvel.dev
  version: v2.0.0
  displayName: "Test Package"
  description: "Package used for testing"
  template: # type of App CR
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
      template:
      - ytt:
          paths:
          - config-step-2-template
          - config-step-2a-overlays
      deploy:
      - kapp: {}
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: InstalledPkg
metadata:
  name: installed-pkg-test
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  pkgRef:
    publicName: pkg1.test.carvel.dev
    version: v2.0.0
  values:
  - secretRef:
      name: simple-values
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-values
stringData:
  values.yml: |
    #@data/values
    ---
    hello_msg: "hi"
