---
apiVersion: package.carvel.dev
kind: Package
metadata:
  name: pkg1.test.carvel.dev.1.0.0
  # cluster scoped
spec:
  publicName: pkg1.test.carvel.dev
  version: 1.0.0
  displayName: "Test Package"
  description: "Package used for testing"
  template: # type of App CR
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
          subPath: config-step-2-template
      template:
      - ytt: {}
      deploy:
      - kapp: {}
---
apiVersion: package.carvel.dev
kind: Package
metadata:
  name: pkg1.test.carvel.dev.2.0.0
  # cluster scoped
spec:
  publicName: pkg1.test.carvel.dev
  version: 2.0.0
  displayName: "Test Package"
  description: "Package used for testing"
  template: # type of App CR
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
      template:
      - ytt:
          paths:
          - config-step-2-template
          - config-step-2a-overlays
      deploy:
      - kapp: {}
---
apiVersion: install.package.carvel.dev
kind: InstalledPackage
metadata:
  name: installed-pkg-test
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  pkgRef:
    publicName: pkg1.test.carvel.dev
    ## explicit
    # version: 1.0.0
    ## latest
    versionSelection: {}
    ## constraint
    # versionSelection:
    #   constraint: "<2.0.0"
  values:
  - secretRef:
      name: simple-values
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-values
stringData:
  values.yml: |
    #@data/values
    ---
    hello_msg: "hi"
