apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: redis
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - helmChart:
      name: redis
      repository:
        url: https://charts.bitnami.com/bitnami
  template:
  - helmTemplate:
      valuesFrom:
      - secretRef:
          name: redis-values
  deploy:
  - kapp:
      delete:
        # Force delete PVCs, since StatefulSet does not delete them
        rawOptions: ["--apply-ignored=true"]
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-values
  namespace: default
stringData:
  data.yml: |
    password: "1234567891234"
