apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-ap2
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - http:
      url: https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip
      subPath: k8s-simple-app-example-master/config-step-2-template
  template:
  - ytt: {}
  deploy:
  - kapp: {}
