// Code generated by main. DO NOT EDIT.

package fake

import (
	v1alpha1 "carvel.dev/kapp-controller/pkg/apis/kappctrl/v1alpha1"
	kappctrlv1alpha1 "carvel.dev/kapp-controller/pkg/client/clientset/versioned/typed/kappctrl/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeApps implements AppInterface
type fakeApps struct {
	*gentype.FakeClientWithList[*v1alpha1.App, *v1alpha1.AppList]
	Fake *FakeKappctrlV1alpha1
}

func newFakeApps(fake *FakeKappctrlV1alpha1, namespace string) kappctrlv1alpha1.AppInterface {
	return &fakeApps{
		gentype.NewFakeClientWithList[*v1alpha1.App, *v1alpha1.AppList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("apps"),
			v1alpha1.SchemeGroupVersion.WithKind("App"),
			func() *v1alpha1.App { return &v1alpha1.App{} },
			func() *v1alpha1.AppList { return &v1alpha1.AppList{} },
			func(dst, src *v1alpha1.AppList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.AppList) []*v1alpha1.App { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.AppList, items []*v1alpha1.App) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
