apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - git:
      url: https://github.com/k14s/k8s-simple-app-example
      ref: origin/develop
      subPath: config-step-2-template
  template:
  - ytt:
      valuesFrom:
      - downwardAPI:
          items:
            - name: ns
              fieldPath: metadata.namespace
            - name: k8sV
              kubernetesVersion: {}
            - name: kcV
              kappControllerVersion: {}
            - name: k8sApis
              kubernetesAPIs: {}
      inline:
        paths:
          filename.yaml: |
            #@ load("@ytt:overlay", "overlay")
            #@ load("@ytt:data", "data")
            #@overlay/match by=overlay.subset({"kind": "Deployment"})
            ---
            spec:
              template:
                spec:
                  containers:
                  #@overlay/match by="name"
                  - name: simple-app
                    env:
                    #@overlay/match by="name"
                    - name: HELLO_MSG
                      value: #@ "from {} namespace, deployed by kapp-controller v{}, hosted on kubernetes v{}, supporting api-versions {}".format(data.values.ns, data.values.kcV, data.values.k8sV, data.values.k8sApis)
  #! sample output: <h1>Hello from default namespace, deployed by kapp-controller v0.40.0+develop, hosted on kubernetes v1.23.3, supporting api-versions ["data.packaging.carvel.dev/v1alpha1", "apps/v1"] ...</h1>
  deploy:
  - kapp: {}
