// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	kappctrlv1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl/v1alpha1"
	versioned "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/listers/kappctrl/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PkgInformer provides access to a shared informer and lister for
// Pkgs.
type PkgInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PkgLister
}

type pkgInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPkgInformer constructs a new informer for Pkg type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPkgInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPkgInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPkgInformer constructs a new informer for Pkg type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPkgInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KappctrlV1alpha1().Pkgs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KappctrlV1alpha1().Pkgs(namespace).Watch(options)
			},
		},
		&kappctrlv1alpha1.Pkg{},
		resyncPeriod,
		indexers,
	)
}

func (f *pkgInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPkgInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pkgInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kappctrlv1alpha1.Pkg{}, f.defaultInformer)
}

func (f *pkgInformer) Lister() v1alpha1.PkgLister {
	return v1alpha1.NewPkgLister(f.Informer().GetIndexer())
}
