// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	kappctrlv1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl/v1alpha1"
	versioned "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/listers/kappctrl/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PkgRepositoryInformer provides access to a shared informer and lister for
// PkgRepositories.
type PkgRepositoryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PkgRepositoryLister
}

type pkgRepositoryInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPkgRepositoryInformer constructs a new informer for PkgRepository type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPkgRepositoryInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPkgRepositoryInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPkgRepositoryInformer constructs a new informer for PkgRepository type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPkgRepositoryInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KappctrlV1alpha1().PkgRepositories().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KappctrlV1alpha1().PkgRepositories().Watch(options)
			},
		},
		&kappctrlv1alpha1.PkgRepository{},
		resyncPeriod,
		indexers,
	)
}

func (f *pkgRepositoryInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPkgRepositoryInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pkgRepositoryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kappctrlv1alpha1.PkgRepository{}, f.defaultInformer)
}

func (f *pkgRepositoryInformer) Lister() v1alpha1.PkgRepositoryLister {
	return v1alpha1.NewPkgRepositoryLister(f.Informer().GetIndexer())
}
