// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	datapackagingv1alpha1 "carvel.dev/kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PackageMetadataLister helps list PackageMetadatas.
// All objects returned here must be treated as read-only.
type PackageMetadataLister interface {
	// List lists all PackageMetadatas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*datapackagingv1alpha1.PackageMetadata, err error)
	// PackageMetadatas returns an object that can list and get PackageMetadatas.
	PackageMetadatas(namespace string) PackageMetadataNamespaceLister
	PackageMetadataListerExpansion
}

// foo_PackageMetadataLister implements the PackageMetadataLister interface.
type foo_PackageMetadataLister struct {
	listers.ResourceIndexer[*datapackagingv1alpha1.PackageMetadata]
}

// NewPackageMetadataLister returns a new PackageMetadataLister.
func NewPackageMetadataLister(indexer cache.Indexer) PackageMetadataLister {
	return &foo_PackageMetadataLister{listers.New[*datapackagingv1alpha1.PackageMetadata](indexer, datapackagingv1alpha1.Resource("packagemetadata"))}
}

// PackageMetadatas returns an object that can list and get PackageMetadatas.
func (s *foo_PackageMetadataLister) PackageMetadatas(namespace string) PackageMetadataNamespaceLister {
	return foo_PackageMetadataNamespaceLister{listers.NewNamespaced[*datapackagingv1alpha1.PackageMetadata](s.ResourceIndexer, namespace)}
}

// PackageMetadataNamespaceLister helps list and get PackageMetadatas.
// All objects returned here must be treated as read-only.
type PackageMetadataNamespaceLister interface {
	// List lists all PackageMetadatas in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*datapackagingv1alpha1.PackageMetadata, err error)
	// Get retrieves the PackageMetadata from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*datapackagingv1alpha1.PackageMetadata, error)
	PackageMetadataNamespaceListerExpansion
}

// foo_PackageMetadataNamespaceLister implements the PackageMetadataNamespaceLister
// interface.
type foo_PackageMetadataNamespaceLister struct {
	listers.ResourceIndexer[*datapackagingv1alpha1.PackageMetadata]
}
