// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PkgLister helps list Pkgs.
type PkgLister interface {
	// List lists all Pkgs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.Pkg, err error)
	// Get retrieves the Pkg from the index for a given name.
	Get(name string) (*v1alpha1.Pkg, error)
	PkgListerExpansion
}

// pkgLister implements the PkgLister interface.
type pkgLister struct {
	indexer cache.Indexer
}

// NewPkgLister returns a new PkgLister.
func NewPkgLister(indexer cache.Indexer) PkgLister {
	return &pkgLister{indexer: indexer}
}

// List lists all Pkgs in the indexer.
func (s *pkgLister) List(selector labels.Selector) (ret []*v1alpha1.Pkg, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Pkg))
	})
	return ret, err
}

// Get retrieves the Pkg from the index for a given name.
func (s *pkgLister) Get(name string) (*v1alpha1.Pkg, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pkg"), name)
	}
	return obj.(*v1alpha1.Pkg), nil
}
