---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  # This is just the resource name and shouldn't be used to reference this package
  # in other resources
  name: pkg.test.carvel.dev.1.0.0
  # cluster scoped
spec:
  # This is the name we want to reference in resources such as InstalledPackage.
  publicName: pkg.test.carvel.dev
  version: 1.0.0
  displayName: "Test Package in repo"
  description: "Package used for testing"
  template:
    # This is just an app template that will be combined with any values given in the
    # InstalledPackage and turned in to an App CR in the cluster. kapp-controller will then
    # reconcile the resulting App CR just like any other, resulting in the installation of
    # our simple app.
    spec:
      fetch:
      - imgpkgBundle:
          image: k8slt/kctrl-example-pkg:v1.0.0
      template:
      - ytt:
          paths:
          - "config.yml"
          - "values.yml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
