// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/internalpackaging/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InternalPackageVersionsGetter has a method to return a InternalPackageVersionInterface.
// A group's client should implement this interface.
type InternalPackageVersionsGetter interface {
	InternalPackageVersions(namespace string) InternalPackageVersionInterface
}

// InternalPackageVersionInterface has methods to work with InternalPackageVersion resources.
type InternalPackageVersionInterface interface {
	Create(ctx context.Context, internalPackageVersion *v1alpha1.InternalPackageVersion, opts v1.CreateOptions) (*v1alpha1.InternalPackageVersion, error)
	Update(ctx context.Context, internalPackageVersion *v1alpha1.InternalPackageVersion, opts v1.UpdateOptions) (*v1alpha1.InternalPackageVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InternalPackageVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InternalPackageVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InternalPackageVersion, err error)
	InternalPackageVersionExpansion
}

// internalPackageVersions implements InternalPackageVersionInterface
type internalPackageVersions struct {
	client rest.Interface
	ns     string
}

// newInternalPackageVersions returns a InternalPackageVersions
func newInternalPackageVersions(c *InternalV1alpha1Client, namespace string) *internalPackageVersions {
	return &internalPackageVersions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the internalPackageVersion, and returns the corresponding internalPackageVersion object, and an error if there is any.
func (c *internalPackageVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InternalPackageVersion, err error) {
	result = &v1alpha1.InternalPackageVersion{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("internalpackageversions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InternalPackageVersions that match those selectors.
func (c *internalPackageVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InternalPackageVersionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InternalPackageVersionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("internalpackageversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested internalPackageVersions.
func (c *internalPackageVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("internalpackageversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a internalPackageVersion and creates it.  Returns the server's representation of the internalPackageVersion, and an error, if there is any.
func (c *internalPackageVersions) Create(ctx context.Context, internalPackageVersion *v1alpha1.InternalPackageVersion, opts v1.CreateOptions) (result *v1alpha1.InternalPackageVersion, err error) {
	result = &v1alpha1.InternalPackageVersion{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("internalpackageversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(internalPackageVersion).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a internalPackageVersion and updates it. Returns the server's representation of the internalPackageVersion, and an error, if there is any.
func (c *internalPackageVersions) Update(ctx context.Context, internalPackageVersion *v1alpha1.InternalPackageVersion, opts v1.UpdateOptions) (result *v1alpha1.InternalPackageVersion, err error) {
	result = &v1alpha1.InternalPackageVersion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("internalpackageversions").
		Name(internalPackageVersion.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(internalPackageVersion).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the internalPackageVersion and deletes it. Returns an error if one occurs.
func (c *internalPackageVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("internalpackageversions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *internalPackageVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("internalpackageversions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched internalPackageVersion.
func (c *internalPackageVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InternalPackageVersion, err error) {
	result = &v1alpha1.InternalPackageVersion{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("internalpackageversions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
