// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// PackageMetadatas returns a PackageMetadataInformer.
	PackageMetadatas() PackageMetadataInformer
	// PackageVersions returns a PackageVersionInformer.
	PackageVersions() PackageVersionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// PackageMetadatas returns a PackageMetadataInformer.
func (v *version) PackageMetadatas() PackageMetadataInformer {
	return &packageMetadataInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PackageVersions returns a PackageVersionInformer.
func (v *version) PackageVersions() PackageVersionInformer {
	return &packageVersionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
