#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Sources"})
---
sources:
#@overlay/replace
#@overlay/match by=overlay.subset({"image": "kapp-controller"})
- image: kapp-controller
  path: .
  docker:
    build:
      file: Dockerfile.dev
