// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	datapackagingv1alpha1 "carvel.dev/kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	scheme "carvel.dev/kapp-controller/pkg/apiserver/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PackagesGetter has a method to return a PackageInterface.
// A group's client should implement this interface.
type PackagesGetter interface {
	Packages(namespace string) PackageInterface
}

// PackageInterface has methods to work with Package resources.
type PackageInterface interface {
	Create(ctx context.Context, foo_Package *datapackagingv1alpha1.Package, opts v1.CreateOptions) (*datapackagingv1alpha1.Package, error)
	Update(ctx context.Context, foo_Package *datapackagingv1alpha1.Package, opts v1.UpdateOptions) (*datapackagingv1alpha1.Package, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*datapackagingv1alpha1.Package, error)
	List(ctx context.Context, opts v1.ListOptions) (*datapackagingv1alpha1.PackageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *datapackagingv1alpha1.Package, err error)
	PackageExpansion
}

// packages implements PackageInterface
type packages struct {
	*gentype.ClientWithList[*datapackagingv1alpha1.Package, *datapackagingv1alpha1.PackageList]
}

// newPackages returns a Packages
func newPackages(c *DataV1alpha1Client, namespace string) *packages {
	return &packages{
		gentype.NewClientWithList[*datapackagingv1alpha1.Package, *datapackagingv1alpha1.PackageList](
			"packages",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *datapackagingv1alpha1.Package { return &datapackagingv1alpha1.Package{} },
			func() *datapackagingv1alpha1.PackageList { return &datapackagingv1alpha1.PackageList{} },
		),
	}
}
