// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "carvel.dev/kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	scheme "carvel.dev/kapp-controller/pkg/apiserver/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PackageMetadatasGetter has a method to return a PackageMetadataInterface.
// A group's client should implement this interface.
type PackageMetadatasGetter interface {
	PackageMetadatas(namespace string) PackageMetadataInterface
}

// PackageMetadataInterface has methods to work with PackageMetadata resources.
type PackageMetadataInterface interface {
	Create(ctx context.Context, foo_PackageMetadata *v1alpha1.PackageMetadata, opts v1.CreateOptions) (*v1alpha1.PackageMetadata, error)
	Update(ctx context.Context, foo_PackageMetadata *v1alpha1.PackageMetadata, opts v1.UpdateOptions) (*v1alpha1.PackageMetadata, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PackageMetadata, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PackageMetadataList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PackageMetadata, err error)
	PackageMetadataExpansion
}

// packageMetadatas implements PackageMetadataInterface
type packageMetadatas struct {
	client rest.Interface
	ns     string
}

// newPackageMetadatas returns a PackageMetadatas
func newPackageMetadatas(c *DataV1alpha1Client, namespace string) *packageMetadatas {
	return &packageMetadatas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the foo_PackageMetadata, and returns the corresponding foo_PackageMetadata object, and an error if there is any.
func (c *packageMetadatas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PackageMetadata, err error) {
	result = &v1alpha1.PackageMetadata{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packagemetadatas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PackageMetadatas that match those selectors.
func (c *packageMetadatas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PackageMetadataList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PackageMetadataList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("packagemetadatas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested packageMetadatas.
func (c *packageMetadatas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("packagemetadatas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a foo_PackageMetadata and creates it.  Returns the server's representation of the foo_PackageMetadata, and an error, if there is any.
func (c *packageMetadatas) Create(ctx context.Context, foo_PackageMetadata *v1alpha1.PackageMetadata, opts v1.CreateOptions) (result *v1alpha1.PackageMetadata, err error) {
	result = &v1alpha1.PackageMetadata{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("packagemetadatas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(foo_PackageMetadata).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a foo_PackageMetadata and updates it. Returns the server's representation of the foo_PackageMetadata, and an error, if there is any.
func (c *packageMetadatas) Update(ctx context.Context, foo_PackageMetadata *v1alpha1.PackageMetadata, opts v1.UpdateOptions) (result *v1alpha1.PackageMetadata, err error) {
	result = &v1alpha1.PackageMetadata{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("packagemetadatas").
		Name(foo_PackageMetadata.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(foo_PackageMetadata).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the foo_PackageMetadata and deletes it. Returns an error if one occurs.
func (c *packageMetadatas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packagemetadatas").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *packageMetadatas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("packagemetadatas").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched foo_PackageMetadata.
func (c *packageMetadatas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PackageMetadata, err error) {
	result = &v1alpha1.PackageMetadata{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("packagemetadatas").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
