// Code generated by main. DO NOT EDIT.

package fake

import (
	v1alpha1 "carvel.dev/kapp-controller/pkg/apis/internalpackaging/v1alpha1"
	internalpackagingv1alpha1 "carvel.dev/kapp-controller/pkg/client/clientset/versioned/typed/internalpackaging/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeInternalPackages implements InternalPackageInterface
type fakeInternalPackages struct {
	*gentype.FakeClientWithList[*v1alpha1.InternalPackage, *v1alpha1.InternalPackageList]
	Fake *FakeInternalV1alpha1
}

func newFakeInternalPackages(fake *FakeInternalV1alpha1, namespace string) internalpackagingv1alpha1.InternalPackageInterface {
	return &fakeInternalPackages{
		gentype.NewFakeClientWithList[*v1alpha1.InternalPackage, *v1alpha1.InternalPackageList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("internalpackages"),
			v1alpha1.SchemeGroupVersion.WithKind("InternalPackage"),
			func() *v1alpha1.InternalPackage { return &v1alpha1.InternalPackage{} },
			func() *v1alpha1.InternalPackageList { return &v1alpha1.InternalPackageList{} },
			func(dst, src *v1alpha1.InternalPackageList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.InternalPackageList) []*v1alpha1.InternalPackage {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.InternalPackageList, items []*v1alpha1.InternalPackage) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
