// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/client/clientset/versioned/typed/internalpackaging/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeInternalV1alpha1 struct {
	*testing.Fake
}

func (c *FakeInternalV1alpha1) InternalPackageMetadatas(namespace string) v1alpha1.InternalPackageMetadataInterface {
	return &FakeInternalPackageMetadatas{c, namespace}
}

func (c *FakeInternalV1alpha1) InternalPackageVersions(namespace string) v1alpha1.InternalPackageVersionInterface {
	return &FakeInternalPackageVersions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeInternalV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
